import {
  BNCC_HABILIDADES,
  getBNCCHabilidades,
  type BNCCHabilidade,
} from '../../../prompts/bncc-reference';
import type {
  CapabilityInput,
  CapabilityOutput,
  DebugEntry,
} from '../../shared/types';
import { createDataConfirmation, createDataCheck } from '../../shared/types';

interface PesquisarBancoQuestoesParams {
  componente?: string;
  ano_serie?: string;
  tema?: string;
  dificuldade?: 'facil' | 'medio' | 'dificil';
  tipo_questao?: 'multipla_escolha' | 'dissertativa' | 'verdadeiro_falso' | 'todos';
  max_resultados?: number;
  disciplina_extraida?: string;
  turma_extraida?: string;
  tema_limpo?: string;
}

interface QuestaoReferencia {
  id: string;
  enunciado: string;
  tipo: 'multipla_escolha' | 'dissertativa' | 'verdadeiro_falso';
  alternativas?: string[];
  resposta_correta?: string;
  explicacao: string;
  componente: string;
  tema: string;
  dificuldade: 'facil' | 'medio' | 'dificil';
  ano_serie: string;
  habilidade_bncc?: string;
  fonte: string;
}

const BANCO_QUESTOES: QuestaoReferencia[] = [
  {
    id: 'q-mat-001',
    enunciado: 'Uma fração equivalente a 3/4 é:',
    tipo: 'multipla_escolha',
    alternativas: ['a) 6/8', 'b) 5/8', 'c) 9/16', 'd) 4/6'],
    resposta_correta: 'a',
    explicacao: 'Multiplicando numerador e denominador por 2: 3×2/4×2 = 6/8',
    componente: 'Matemática',
    tema: 'frações equivalentes',
    dificuldade: 'facil',
    ano_serie: '5º Ano',
    habilidade_bncc: 'EF05MA03',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-002',
    enunciado: 'Resolva a equação: 2x + 5 = 15. Qual o valor de x?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 3', 'b) 5', 'c) 7', 'd) 10'],
    resposta_correta: 'b',
    explicacao: '2x + 5 = 15 → 2x = 10 → x = 5',
    componente: 'Matemática',
    tema: 'equações do 1º grau',
    dificuldade: 'facil',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07MA18',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-003',
    enunciado: 'Qual é a área de um triângulo com base 10 cm e altura 6 cm?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 16 cm²', 'b) 30 cm²', 'c) 60 cm²', 'd) 20 cm²'],
    resposta_correta: 'b',
    explicacao: 'Área = (base × altura) / 2 = (10 × 6) / 2 = 30 cm²',
    componente: 'Matemática',
    tema: 'geometria plana',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08MA19',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-004',
    enunciado: 'Determine as raízes da equação x² - 5x + 6 = 0.',
    tipo: 'dissertativa',
    explicacao: 'Usando a fórmula de Bhaskara ou fatoração: (x-2)(x-3) = 0, logo x = 2 ou x = 3',
    componente: 'Matemática',
    tema: 'equações do 2º grau',
    dificuldade: 'medio',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09MA09',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-005',
    enunciado: 'O gráfico da função f(x) = 2x - 4 intercepta o eixo x no ponto:',
    tipo: 'multipla_escolha',
    alternativas: ['a) (0, -4)', 'b) (2, 0)', 'c) (-2, 0)', 'd) (4, 0)'],
    resposta_correta: 'b',
    explicacao: 'Para interceptar o eixo x, f(x) = 0: 2x - 4 = 0 → x = 2. Ponto: (2, 0)',
    componente: 'Matemática',
    tema: 'funções do 1º grau',
    dificuldade: 'medio',
    ano_serie: 'Ensino Médio',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-001',
    enunciado: 'Qual a principal função das mitocôndrias nas células?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Síntese de proteínas', 'b) Produção de energia (ATP)', 'c) Armazenamento de água', 'd) Digestão celular'],
    resposta_correta: 'b',
    explicacao: 'As mitocôndrias são responsáveis pela respiração celular, produzindo ATP (energia) para a célula',
    componente: 'Ciências',
    tema: 'célula e organelas',
    dificuldade: 'facil',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07CI01',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-002',
    enunciado: 'A fotossíntese é um processo realizado pelas plantas que transforma:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Oxigênio em gás carbônico', 'b) Energia luminosa em energia química', 'c) Água em minerais', 'd) Proteínas em carboidratos'],
    resposta_correta: 'b',
    explicacao: 'Na fotossíntese, a planta absorve luz solar e CO₂, produzindo glicose (energia química) e O₂',
    componente: 'Ciências',
    tema: 'fotossíntese',
    dificuldade: 'facil',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07CI06',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-003',
    enunciado: 'Explique a diferença entre calor e temperatura, dando um exemplo prático.',
    tipo: 'dissertativa',
    explicacao: 'Calor é a transferência de energia térmica entre corpos, enquanto temperatura é a medida da agitação das moléculas. Exemplo: uma xícara de café quente transfere calor para a mão (calor), e o termômetro mede a temperatura.',
    componente: 'Ciências',
    tema: 'calor e temperatura',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07CI02',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-004',
    enunciado: 'Quais são os níveis de organização de um ecossistema, do mais simples ao mais complexo?',
    tipo: 'dissertativa',
    explicacao: 'Organismo → População → Comunidade → Ecossistema → Bioma → Biosfera',
    componente: 'Ciências',
    tema: 'ecossistemas',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07CI07',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-001',
    enunciado: 'A Revolução Francesa (1789) teve como principal causa:',
    tipo: 'multipla_escolha',
    alternativas: ['a) A invasão napoleônica', 'b) A crise econômica e a desigualdade social do Antigo Regime', 'c) A Guerra dos Cem Anos', 'd) A reforma protestante'],
    resposta_correta: 'b',
    explicacao: 'A Revolução Francesa foi motivada pela crise do Antigo Regime, com desigualdade entre estamentos, crise fiscal e influência das ideias iluministas',
    componente: 'História',
    tema: 'revolução francesa',
    dificuldade: 'facil',
    ano_serie: '8º Ano',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-002',
    enunciado: 'Qual foi o principal objetivo da Proclamação da República no Brasil em 1889?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Abolir a escravidão', 'b) Substituir a monarquia por um regime republicano', 'c) Declarar independência de Portugal', 'd) Criar uma nova constituição imperial'],
    resposta_correta: 'b',
    explicacao: 'A Proclamação da República em 15 de novembro de 1889 depôs o Imperador D. Pedro II e instaurou o regime republicano no Brasil',
    componente: 'História',
    tema: 'república brasileira',
    dificuldade: 'facil',
    ano_serie: '9º Ano',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-001',
    enunciado: 'O bioma Cerrado é considerado a "savana brasileira". Quais são duas de suas principais características?',
    tipo: 'dissertativa',
    explicacao: 'O Cerrado apresenta vegetação com árvores de troncos retorcidos e raízes profundas, clima tropical sazonal com duas estações bem definidas (seca e chuvosa), e é o segundo maior bioma do Brasil',
    componente: 'Geografia',
    tema: 'biomas brasileiros',
    dificuldade: 'facil',
    ano_serie: '7º Ano',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-002',
    enunciado: 'A urbanização acelerada no Brasil gerou diversos problemas. Cite e explique dois deles.',
    tipo: 'dissertativa',
    explicacao: 'Exemplos: 1) Favelização — o crescimento urbano sem planejamento levou à formação de habitações precárias em áreas de risco. 2) Trânsito — o aumento da frota veicular sem infraestrutura adequada causa congestionamentos e poluição',
    componente: 'Geografia',
    tema: 'urbanização',
    dificuldade: 'medio',
    ano_serie: '9º Ano',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-001',
    enunciado: 'Na frase "Os alunos estudaram bastante para a prova", o sujeito é:',
    tipo: 'multipla_escolha',
    alternativas: ['a) estudaram', 'b) bastante', 'c) Os alunos', 'd) para a prova'],
    resposta_correta: 'c',
    explicacao: 'O sujeito é "Os alunos", pois é quem pratica a ação de estudar',
    componente: 'Língua Portuguesa',
    tema: 'análise sintática',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-002',
    enunciado: 'Leia o trecho e identifique o tipo de narrador: "Maria abriu a porta e sentiu o vento frio. Ela pensou que deveria ter trazido um casaco."',
    tipo: 'multipla_escolha',
    alternativas: ['a) Narrador-personagem', 'b) Narrador-observador', 'c) Narrador onisciente', 'd) Narrador-testemunha'],
    resposta_correta: 'c',
    explicacao: 'O narrador é onisciente porque conhece os pensamentos da personagem ("Ela pensou que...")',
    componente: 'Língua Portuguesa',
    tema: 'tipos de narrador',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-006',
    enunciado: 'Um produto que custava R$ 200,00 teve um desconto de 15%. Qual é o novo preço do produto?',
    tipo: 'multipla_escolha',
    alternativas: ['a) R$ 170,00', 'b) R$ 185,00', 'c) R$ 150,00', 'd) R$ 175,00'],
    resposta_correta: 'a',
    explicacao: '15% de 200 = 0,15 × 200 = 30. Novo preço: 200 - 30 = R$ 170,00',
    componente: 'Matemática',
    tema: 'porcentagem',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06MA13',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-007',
    enunciado: 'Em uma receita, a razão entre farinha e açúcar é de 3 para 2. Se forem usados 600 g de farinha, quantos gramas de açúcar serão necessários?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 300 g', 'b) 400 g', 'c) 200 g', 'd) 500 g'],
    resposta_correta: 'b',
    explicacao: '3/2 = 600/x → x = (600 × 2) / 3 = 400 g de açúcar',
    componente: 'Matemática',
    tema: 'razão e proporção',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07MA17',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-008',
    enunciado: 'Um triângulo retângulo possui catetos medindo 3 cm e 4 cm. Qual é a medida da hipotenusa?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 6 cm', 'b) 7 cm', 'c) 5 cm', 'd) 8 cm'],
    resposta_correta: 'c',
    explicacao: 'Pelo Teorema de Pitágoras: h² = 3² + 4² = 9 + 16 = 25 → h = 5 cm',
    componente: 'Matemática',
    tema: 'teorema de Pitágoras',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08MA19',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-009',
    enunciado: 'Uma urna contém 3 bolas vermelhas, 5 bolas azuis e 2 bolas verdes. Qual a probabilidade de sortear uma bola azul?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 1/2', 'b) 3/10', 'c) 2/5', 'd) 1/5'],
    resposta_correta: 'a',
    explicacao: 'Total de bolas: 3 + 5 + 2 = 10. Probabilidade de azul: 5/10 = 1/2',
    componente: 'Matemática',
    tema: 'probabilidade',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08MA22',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-010',
    enunciado: 'Um aluno obteve as seguintes notas nas provas bimestrais: 7,0; 8,5; 6,0 e 9,5. Calcule a média aritmética e explique se o aluno foi aprovado considerando média mínima 7,0.',
    tipo: 'dissertativa',
    explicacao: 'Média = (7,0 + 8,5 + 6,0 + 9,5) / 4 = 31,0 / 4 = 7,75. Como 7,75 ≥ 7,0, o aluno foi aprovado.',
    componente: 'Matemática',
    tema: 'estatística e médias',
    dificuldade: 'medio',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09MA05',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-011',
    enunciado: 'Qual é a soma dos ângulos internos de um hexágono regular?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 360°', 'b) 540°', 'c) 720°', 'd) 900°'],
    resposta_correta: 'c',
    explicacao: 'Soma dos ângulos internos = (n - 2) × 180° = (6 - 2) × 180° = 4 × 180° = 720°',
    componente: 'Matemática',
    tema: 'polígonos',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06MA20',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-012',
    enunciado: 'Qual o resultado de 3,45 + 2,7?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 5,15', 'b) 6,15', 'c) 6,42', 'd) 5,72'],
    resposta_correta: 'b',
    explicacao: 'Alinhando as casas decimais: 3,45 + 2,70 = 6,15',
    componente: 'Matemática',
    tema: 'números decimais',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06MA11',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-013',
    enunciado: 'Resolva a expressão numérica: 3 + 2 × (8 - 3) - 4. Apresente o passo a passo.',
    tipo: 'dissertativa',
    explicacao: 'Primeiro os parênteses: 8 - 3 = 5. Depois a multiplicação: 2 × 5 = 10. Depois soma e subtração da esquerda para a direita: 3 + 10 - 4 = 9.',
    componente: 'Matemática',
    tema: 'expressões numéricas',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06MA03',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-014',
    enunciado: 'Dois ângulos são suplementares. Se um deles mede 65°, quanto mede o outro?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 25°', 'b) 115°', 'c) 90°', 'd) 125°'],
    resposta_correta: 'b',
    explicacao: 'Ângulos suplementares somam 180°. Logo: 180° - 65° = 115°',
    componente: 'Matemática',
    tema: 'ângulos',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07MA23',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-015',
    enunciado: 'Qual é o valor de 2⁵?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 10', 'b) 25', 'c) 32', 'd) 64'],
    resposta_correta: 'c',
    explicacao: '2⁵ = 2 × 2 × 2 × 2 × 2 = 32',
    componente: 'Matemática',
    tema: 'potenciação',
    dificuldade: 'facil',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07MA04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-016',
    enunciado: 'Qual é o MMC (Mínimo Múltiplo Comum) entre 12 e 18?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 24', 'b) 36', 'c) 48', 'd) 72'],
    resposta_correta: 'b',
    explicacao: 'Decompondo: 12 = 2² × 3 e 18 = 2 × 3². MMC = 2² × 3² = 4 × 9 = 36',
    componente: 'Matemática',
    tema: 'MMC e MDC',
    dificuldade: 'medio',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06MA05',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-017',
    enunciado: 'Uma pessoa aplicou R$ 2.000,00 a uma taxa de juros simples de 3% ao mês durante 5 meses. Calcule o montante final e explique cada etapa.',
    tipo: 'dissertativa',
    explicacao: 'Juros = C × i × t = 2000 × 0,03 × 5 = R$ 300,00. Montante = Capital + Juros = 2000 + 300 = R$ 2.300,00',
    componente: 'Matemática',
    tema: 'juros simples',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09MA05',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-018',
    enunciado: 'Qual é o volume de um prisma retangular com dimensões 5 cm, 3 cm e 8 cm?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 16 cm³', 'b) 120 cm³', 'c) 80 cm³', 'd) 150 cm³'],
    resposta_correta: 'b',
    explicacao: 'Volume = comprimento × largura × altura = 5 × 3 × 8 = 120 cm³',
    componente: 'Matemática',
    tema: 'volume de prismas',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08MA21',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-019',
    enunciado: 'A distância da Terra ao Sol é de aproximadamente 150.000.000 km. Como esse número é escrito em notação científica?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 15 × 10⁷ km', 'b) 1,5 × 10⁸ km', 'c) 1,5 × 10⁷ km', 'd) 150 × 10⁶ km'],
    resposta_correta: 'b',
    explicacao: '150.000.000 = 1,5 × 10⁸. Em notação científica, o número deve ter apenas um algarismo antes da vírgula.',
    componente: 'Matemática',
    tema: 'notação científica',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09MA04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-mat-020',
    enunciado: 'Duas grandezas são diretamente proporcionais. Quando uma vale 4, a outra vale 10. Explique o conceito e determine o valor da segunda grandeza quando a primeira vale 12.',
    tipo: 'dissertativa',
    explicacao: 'Grandezas diretamente proporcionais mantêm razão constante: 4/10 = 12/x → x = (12 × 10) / 4 = 30. Quando a primeira grandeza triplica (de 4 para 12), a segunda também triplica (de 10 para 30).',
    componente: 'Matemática',
    tema: 'grandezas proporcionais',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07MA17',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-005',
    enunciado: 'No sistema digestório, qual órgão é responsável pela absorção da maior parte dos nutrientes?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Estômago', 'b) Intestino grosso', 'c) Intestino delgado', 'd) Esôfago'],
    resposta_correta: 'c',
    explicacao: 'O intestino delgado, com suas vilosidades intestinais, é responsável pela absorção da maior parte dos nutrientes digeridos para a corrente sanguínea.',
    componente: 'Ciências',
    tema: 'sistema digestório',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08CI07',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-006',
    enunciado: 'Uma mistura de água e sal de cozinha dissolvido é classificada como:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Substância pura simples', 'b) Substância pura composta', 'c) Mistura heterogênea', 'd) Mistura homogênea'],
    resposta_correta: 'd',
    explicacao: 'Água com sal dissolvido forma uma mistura homogênea (solução), pois apresenta uma única fase visível, apesar de ser composta por duas substâncias.',
    componente: 'Ciências',
    tema: 'substâncias puras e misturas',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06CI01',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-007',
    enunciado: 'A passagem da água do estado líquido para o estado gasoso é chamada de:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Fusão', 'b) Solidificação', 'c) Condensação', 'd) Evaporação'],
    resposta_correta: 'd',
    explicacao: 'A evaporação (ou vaporização) é a mudança do estado líquido para o gasoso. Fusão é de sólido para líquido, solidificação é de líquido para sólido e condensação é de gasoso para líquido.',
    componente: 'Ciências',
    tema: 'estados da matéria',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06CI02',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-008',
    enunciado: 'Explique a diferença entre os planetas rochosos e os planetas gasosos do Sistema Solar, citando ao menos dois exemplos de cada tipo.',
    tipo: 'dissertativa',
    explicacao: 'Planetas rochosos (telúricos) possuem superfície sólida: Mercúrio, Vênus, Terra e Marte. Planetas gasosos (jovianos) são compostos principalmente de gases e não possuem superfície sólida definida: Júpiter, Saturno, Urano e Netuno. Os rochosos são menores e mais próximos do Sol, enquanto os gasosos são maiores e mais distantes.',
    componente: 'Ciências',
    tema: 'sistema solar',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06CI13',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-009',
    enunciado: 'Em uma cadeia alimentar, os organismos que decompõem a matéria orgânica morta são chamados de:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Produtores', 'b) Consumidores primários', 'c) Consumidores terciários', 'd) Decompositores'],
    resposta_correta: 'd',
    explicacao: 'Os decompositores (fungos e bactérias) são responsáveis pela decomposição da matéria orgânica morta, devolvendo nutrientes ao solo e reiniciando o ciclo da matéria.',
    componente: 'Ciências',
    tema: 'cadeia alimentar',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07CI07',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-010',
    enunciado: 'Na tabela periódica, os elementos do grupo 18 (gases nobres) são conhecidos por sua baixa reatividade. Qual das alternativas apresenta APENAS gases nobres?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Hélio, Nitrogênio e Argônio', 'b) Hélio, Neônio e Argônio', 'c) Oxigênio, Neônio e Xenônio', 'd) Hidrogênio, Hélio e Criptônio'],
    resposta_correta: 'b',
    explicacao: 'Hélio (He), Neônio (Ne) e Argônio (Ar) são todos gases nobres do grupo 18. Nitrogênio, Oxigênio e Hidrogênio pertencem a outros grupos.',
    componente: 'Ciências',
    tema: 'tabela periódica',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09CI01',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-011',
    enunciado: 'Explique como as ondas sonoras se propagam e por que não é possível ouvir sons no espaço sideral (vácuo).',
    tipo: 'dissertativa',
    explicacao: 'As ondas sonoras são ondas mecânicas que precisam de um meio material (sólido, líquido ou gasoso) para se propagar, pois se transmitem pela vibração das partículas do meio. No vácuo do espaço sideral não há partículas, portanto as ondas sonoras não conseguem se propagar.',
    componente: 'Ciências',
    tema: 'ondas sonoras',
    dificuldade: 'medio',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09CI06',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-012',
    enunciado: 'Na reprodução humana, a fecundação ocorre normalmente em qual estrutura do sistema reprodutor feminino?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Útero', 'b) Ovário', 'c) Tuba uterina', 'd) Vagina'],
    resposta_correta: 'c',
    explicacao: 'A fecundação normalmente ocorre na tuba uterina (ou trompa de Falópio), onde o espermatozoide encontra o óvulo. Após a fecundação, o zigoto se desloca até o útero para a implantação.',
    componente: 'Ciências',
    tema: 'reprodução humana',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08CI09',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-013',
    enunciado: 'Diferencie os quatro tipos básicos de tecidos do corpo humano (epitelial, conjuntivo, muscular e nervoso), descrevendo a principal função de cada um.',
    tipo: 'dissertativa',
    explicacao: 'Tecido epitelial: reveste superfícies e forma glândulas (proteção e secreção). Tecido conjuntivo: sustenta e conecta outros tecidos (osso, cartilagem, sangue). Tecido muscular: responsável pela contração e movimentação (esquelético, cardíaco e liso). Tecido nervoso: transmite impulsos nervosos, coordenando as funções do organismo.',
    componente: 'Ciências',
    tema: 'tecidos humanos',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08CI08',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-014',
    enunciado: 'Qual bioma brasileiro é caracterizado por apresentar vegetação densa, clima equatorial quente e úmido e a maior biodiversidade do planeta?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Cerrado', 'b) Caatinga', 'c) Amazônia', 'd) Mata Atlântica'],
    resposta_correta: 'c',
    explicacao: 'A Amazônia é o maior bioma brasileiro, com floresta tropical densa, clima equatorial (quente e úmido) e a maior biodiversidade do planeta, abrigando milhões de espécies.',
    componente: 'Ciências',
    tema: 'biomas brasileiros',
    dificuldade: 'facil',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07CI07',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-015',
    enunciado: 'Qual das alternativas representa uma transformação química?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Derreter gelo', 'b) Dissolver sal na água', 'c) Queimar papel', 'd) Amassar uma lata'],
    resposta_correta: 'c',
    explicacao: 'Queimar papel é uma transformação química (combustão) pois há formação de novas substâncias (cinzas, CO₂, vapor de água) com alteração da composição. As demais são transformações físicas.',
    componente: 'Ciências',
    tema: 'transformações químicas',
    dificuldade: 'medio',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09CI02',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-016',
    enunciado: 'Uma alavanca é um tipo de máquina simples. Qual é a principal vantagem de seu uso?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Eliminar o atrito', 'b) Multiplicar a força aplicada', 'c) Criar energia', 'd) Aumentar a velocidade da luz'],
    resposta_correta: 'b',
    explicacao: 'A alavanca é uma máquina simples que permite multiplicar a força aplicada, facilitando mover ou levantar objetos pesados com menor esforço, como ao usar uma chave de fenda ou um alicate.',
    componente: 'Ciências',
    tema: 'máquinas simples',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07CI04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-017',
    enunciado: 'Descreva a organização do sistema nervoso central e do sistema nervoso periférico, explicando a função de cada divisão e como se comunicam.',
    tipo: 'dissertativa',
    explicacao: 'O sistema nervoso central (SNC) é composto pelo encéfalo (cérebro, cerebelo e tronco encefálico) e pela medula espinhal, sendo responsável por processar informações e coordenar respostas. O sistema nervoso periférico (SNP) é formado por nervos e gânglios que conectam o SNC ao restante do corpo, transmitindo impulsos sensoriais e motores.',
    componente: 'Ciências',
    tema: 'sistema nervoso',
    dificuldade: 'dificil',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08CI07',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-cie-018',
    enunciado: 'A unidade de medida de energia elétrica cobrada na conta de luz é:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Watt (W)', 'b) Ampère (A)', 'c) Quilowatt-hora (kWh)', 'd) Volt (V)'],
    resposta_correta: 'c',
    explicacao: 'A energia elétrica consumida é medida em quilowatt-hora (kWh), que representa a potência (kW) multiplicada pelo tempo de uso (h). Watt é unidade de potência, Ampère de corrente e Volt de tensão.',
    componente: 'Ciências',
    tema: 'energia elétrica',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08CI04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-003',
    enunciado: 'A democracia, sistema político adotado por muitos países atuais, teve origem na:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Roma Antiga', 'b) Grécia Antiga (Atenas)', 'c) Egito Antigo', 'd) Mesopotâmia'],
    resposta_correta: 'b',
    explicacao: 'A democracia surgiu em Atenas, na Grécia Antiga, por volta do século V a.C., onde cidadãos livres participavam diretamente das decisões políticas na Ágora.',
    componente: 'História',
    tema: 'Grécia Antiga',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06HI07',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-004',
    enunciado: 'No feudalismo, a relação entre suseranos e vassalos era baseada em:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Trabalho assalariado', 'b) Troca de terras por lealdade e serviço militar', 'c) Comércio de escravos', 'd) Eleições democráticas'],
    resposta_correta: 'b',
    explicacao: 'No feudalismo, o suserano cedia terras (feudos) ao vassalo em troca de lealdade, proteção militar e serviços. Essa relação era formalizada pela cerimônia de homenagem.',
    componente: 'História',
    tema: 'feudalismo',
    dificuldade: 'medio',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06HI16',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-005',
    enunciado: 'Qual foi a principal motivação econômica das Grandes Navegações realizadas por Portugal e Espanha nos séculos XV e XVI?',
    tipo: 'multipla_escolha',
    alternativas: ['a) A busca por novas rotas comerciais para as Índias (especiarias)', 'b) A busca por petróleo', 'c) A expansão do protestantismo', 'd) A busca por minério de ferro'],
    resposta_correta: 'a',
    explicacao: 'As Grandes Navegações foram motivadas principalmente pela busca de novas rotas comerciais marítimas para as Índias, visando o comércio de especiarias (pimenta, canela, cravo) que eram extremamente valiosas na Europa.',
    componente: 'História',
    tema: 'grandes navegações',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07HI02',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-006',
    enunciado: 'Explique as principais características da colonização portuguesa no Brasil durante o período colonial (1500-1822), destacando os ciclos econômicos.',
    tipo: 'dissertativa',
    explicacao: 'A colonização portuguesa no Brasil foi marcada pela exploração econômica através de ciclos: pau-brasil (extração inicial), cana-de-açúcar (séculos XVI-XVII, com uso de mão de obra escravizada africana nos engenhos do Nordeste), ouro e pedras preciosas (século XVIII, em Minas Gerais). A economia era baseada no pacto colonial, onde a colônia fornecia matérias-primas à metrópole.',
    componente: 'História',
    tema: 'colonização do Brasil',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07HI09',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-007',
    enunciado: 'A Revolução Industrial, iniciada na Inglaterra no século XVIII, provocou grandes mudanças. Qual alternativa representa uma consequência desse processo?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Redução da produção de mercadorias', 'b) Êxodo rural e crescimento das cidades', 'c) Fim do comércio internacional', 'd) Retorno ao trabalho artesanal'],
    resposta_correta: 'b',
    explicacao: 'A Revolução Industrial provocou o êxodo rural (migração do campo para as cidades), pois as fábricas atraíam trabalhadores, gerando rápido crescimento urbano, muitas vezes sem infraestrutura adequada.',
    componente: 'História',
    tema: 'Revolução Industrial',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08HI01',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-008',
    enunciado: 'Quem proclamou a Independência do Brasil em 7 de setembro de 1822 às margens do rio Ipiranga?',
    tipo: 'multipla_escolha',
    alternativas: ['a) D. João VI', 'b) D. Pedro I', 'c) Tiradentes', 'd) José Bonifácio'],
    resposta_correta: 'b',
    explicacao: 'D. Pedro I proclamou a Independência do Brasil em 7 de setembro de 1822, às margens do rio Ipiranga, em São Paulo, rompendo os laços coloniais com Portugal.',
    componente: 'História',
    tema: 'independência do Brasil',
    dificuldade: 'facil',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08HI11',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-009',
    enunciado: 'Durante a Era Vargas (1930-1945), foram criadas importantes leis trabalhistas. Qual das alternativas apresenta uma conquista desse período?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Voto feminino e CLT (Consolidação das Leis do Trabalho)', 'b) Privatização de todas as empresas estatais', 'c) Abolição da escravidão', 'd) Implantação do regime parlamentarista'],
    resposta_correta: 'a',
    explicacao: 'A Era Vargas criou a CLT (1943), que consolidou os direitos trabalhistas (jornada de trabalho, férias, salário mínimo), e concedeu o direito de voto às mulheres (1932), entre outras reformas.',
    componente: 'História',
    tema: 'Era Vargas',
    dificuldade: 'medio',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09HI02',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-010',
    enunciado: 'Explique o que foi a Guerra Fria, identificando os dois blocos que se opunham, suas ideologias e pelo menos dois eventos marcantes desse período.',
    tipo: 'dissertativa',
    explicacao: 'A Guerra Fria (1947-1991) foi um período de tensão geopolítica entre dois blocos: EUA (bloco capitalista/ocidental) e URSS (bloco socialista/oriental). Não houve conflito militar direto entre as superpotências, mas disputas indiretas. Eventos marcantes: construção do Muro de Berlim (1961), Crise dos Mísseis de Cuba (1962), corrida espacial e Guerra do Vietnã.',
    componente: 'História',
    tema: 'Guerra Fria',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09HI15',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-011',
    enunciado: 'Qual foi o principal sistema de trabalho utilizado nas lavouras de cana-de-açúcar no Brasil colonial?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Trabalho assalariado', 'b) Escravidão de africanos', 'c) Servidão feudal', 'd) Trabalho cooperativo indígena voluntário'],
    resposta_correta: 'b',
    explicacao: 'As lavouras de cana-de-açúcar no Brasil colonial utilizaram principalmente a mão de obra escravizada de africanos trazidos à força pelo tráfico negreiro transatlântico, em condições desumanas.',
    componente: 'História',
    tema: 'escravidão no Brasil',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08HI14',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-012',
    enunciado: 'Descreva ao menos três aspectos da cultura e organização social dos povos indígenas que já habitavam o Brasil antes da chegada dos portugueses em 1500.',
    tipo: 'dissertativa',
    explicacao: 'Os povos indígenas possuíam: 1) Organização social baseada em aldeias com divisão de tarefas (caça, pesca, agricultura, artesanato). 2) Cultura rica com tradições orais, rituais, pinturas corporais e arte plumária. 3) Relação sustentável com a natureza, praticando agricultura de subsistência (mandioca, milho). 4) Diversidade linguística com centenas de línguas e etnias diferentes (Tupi, Guarani, Macro-Jê, entre outras).',
    componente: 'História',
    tema: 'povos indígenas',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06HI08',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-013',
    enunciado: 'O Renascimento Cultural (séculos XIV-XVI) representou uma mudança de mentalidade na Europa. Qual era a principal característica desse movimento?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Valorização da fé acima da razão', 'b) Antropocentrismo e valorização do ser humano e da razão', 'c) Rejeição total da arte clássica greco-romana', 'd) Fortalecimento do poder da Igreja Católica'],
    resposta_correta: 'b',
    explicacao: 'O Renascimento foi marcado pelo antropocentrismo (o ser humano como centro), pela valorização da razão, pelo resgate da cultura greco-romana e pelo desenvolvimento artístico e científico, em contraste com o teocentrismo medieval.',
    componente: 'História',
    tema: 'renascimento',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07HI04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-014',
    enunciado: 'Qual foi o estopim (causa imediata) que desencadeou a Primeira Guerra Mundial em 1914?',
    tipo: 'multipla_escolha',
    alternativas: ['a) A invasão da Polônia pela Alemanha', 'b) O assassinato do arquiduque Francisco Ferdinando da Áustria-Hungria', 'c) O ataque a Pearl Harbor', 'd) A queda do Muro de Berlim'],
    resposta_correta: 'b',
    explicacao: 'O estopim da Primeira Guerra Mundial foi o assassinato do arquiduque Francisco Ferdinando da Áustria-Hungria, em Sarajevo (1914), por um nacionalista sérvio. Isso desencadeou uma reação em cadeia de declarações de guerra entre as alianças europeias.',
    componente: 'História',
    tema: 'primeira guerra mundial',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09HI10',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-015',
    enunciado: 'Explique o contexto político e social que levou ao golpe civil-militar de 1964 no Brasil e suas principais consequências para a democracia brasileira.',
    tipo: 'dissertativa',
    explicacao: 'O golpe de 1964 ocorreu em um contexto de polarização política, tensões sociais e influência da Guerra Fria. O governo de João Goulart, com suas reformas de base, enfrentou oposição de setores militares, empresariais e da classe média. As consequências incluíram: supressão de direitos civis, censura à imprensa, perseguição política, cassação de mandatos, tortura de opositores e a promulgação de atos institucionais (como o AI-5 de 1968). A ditadura perdurou até 1985.',
    componente: 'História',
    tema: 'golpe de 64',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09HI19',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-his-016',
    enunciado: 'As civilizações mesopotâmicas desenvolveram importantes contribuições para a humanidade. Qual invenção é atribuída aos sumérios?',
    tipo: 'multipla_escolha',
    alternativas: ['a) A escrita cuneiforme', 'b) O alfabeto fenício', 'c) Os hieróglifos', 'd) A imprensa'],
    resposta_correta: 'a',
    explicacao: 'Os sumérios, povo da Mesopotâmia, desenvolveram a escrita cuneiforme por volta de 3500 a.C., um dos mais antigos sistemas de escrita da humanidade, feita com marcas em formato de cunha em tabletes de argila.',
    componente: 'História',
    tema: 'civilizações mesopotâmicas',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06HI02',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-003',
    enunciado: 'As placas tectônicas são grandes blocos da litosfera terrestre. O que ocorre nas regiões onde duas placas se encontram?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Formação de desertos', 'b) Terremotos, vulcanismo e formação de montanhas', 'c) Surgimento de novos oceanos instantaneamente', 'd) Diminuição da temperatura global'],
    resposta_correta: 'b',
    explicacao: 'Nas zonas de encontro de placas tectônicas ocorrem fenômenos como terremotos, erupções vulcânicas e formação de cadeias de montanhas (como os Andes e o Himalaia), devido ao atrito e pressão entre as placas.',
    componente: 'Geografia',
    tema: 'placas tectônicas',
    dificuldade: 'medio',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06GE05',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-004',
    enunciado: 'Qual etapa do ciclo da água corresponde à transformação da água líquida em vapor pela ação do calor do Sol?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Precipitação', 'b) Infiltração', 'c) Evaporação', 'd) Condensação'],
    resposta_correta: 'c',
    explicacao: 'A evaporação é a etapa em que a água líquida (de rios, mares, lagos) se transforma em vapor pela ação do calor solar, subindo para a atmosfera e dando continuidade ao ciclo hidrológico.',
    componente: 'Geografia',
    tema: 'ciclo da água',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06GE04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-005',
    enunciado: 'O Brasil possui quantos fusos horários oficiais e qual é a referência internacional para o cálculo dos fusos?',
    tipo: 'multipla_escolha',
    alternativas: ['a) 2 fusos, referência: Linha do Equador', 'b) 4 fusos, referência: Meridiano de Greenwich', 'c) 3 fusos, referência: Trópico de Capricórnio', 'd) 5 fusos, referência: Círculo Polar Ártico'],
    resposta_correta: 'b',
    explicacao: 'O Brasil possui 4 fusos horários oficiais (desde 2013). A referência internacional é o Meridiano de Greenwich (0°), a partir do qual se contam as horas para leste (+) e para oeste (-).',
    componente: 'Geografia',
    tema: 'fusos horários',
    dificuldade: 'medio',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06GE01',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-006',
    enunciado: 'Explique as principais características do clima tropical típico brasileiro, incluindo temperaturas, estações e regiões de ocorrência.',
    tipo: 'dissertativa',
    explicacao: 'O clima tropical típico brasileiro é caracterizado por temperaturas elevadas durante o ano todo (médias acima de 20°C), com duas estações bem definidas: verão chuvoso e inverno seco. Ocorre na região central do Brasil, abrangendo partes dos estados de Goiás, Minas Gerais, São Paulo, Mato Grosso do Sul e Tocantins.',
    componente: 'Geografia',
    tema: 'clima brasileiro',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07GE04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-007',
    enunciado: 'Qual sub-região do Nordeste brasileiro é caracterizada pelo clima semiárido e pela vegetação de caatinga?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Zona da Mata', 'b) Agreste', 'c) Sertão', 'd) Meio-Norte'],
    resposta_correta: 'c',
    explicacao: 'O Sertão é a sub-região nordestina marcada pelo clima semiárido, com chuvas escassas e irregulares, altas temperaturas e vegetação adaptada à seca (caatinga), com plantas xerófilas e cactos.',
    componente: 'Geografia',
    tema: 'região nordeste',
    dificuldade: 'facil',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07GE06',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-008',
    enunciado: 'A migração de nordestinos para o Sudeste do Brasil durante o século XX é um exemplo de:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Emigração internacional', 'b) Migração pendular', 'c) Migração interna inter-regional', 'd) Imigração estrangeira'],
    resposta_correta: 'c',
    explicacao: 'A migração de nordestinos para o Sudeste é uma migração interna inter-regional, ou seja, deslocamento dentro do próprio país, de uma região para outra, motivada por fatores econômicos como busca de emprego e melhores condições de vida.',
    componente: 'Geografia',
    tema: 'migração e imigração',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08GE01',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-009',
    enunciado: 'Discorra sobre os aspectos positivos e negativos da globalização, considerando seus impactos econômicos, culturais e sociais nos países em desenvolvimento.',
    tipo: 'dissertativa',
    explicacao: 'Aspectos positivos: acesso a tecnologias e informação, expansão do comércio internacional, intercâmbio cultural e avanços na comunicação. Aspectos negativos: aumento das desigualdades entre países ricos e pobres, homogeneização cultural (perda de identidades locais), exploração de mão de obra barata, dependência econômica e vulnerabilidade a crises financeiras globais.',
    componente: 'Geografia',
    tema: 'globalização',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09GE05',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-010',
    enunciado: 'A concentração industrial brasileira localiza-se predominantemente em qual região do país?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Norte', 'b) Nordeste', 'c) Sudeste', 'd) Centro-Oeste'],
    resposta_correta: 'c',
    explicacao: 'A região Sudeste concentra a maior parte do parque industrial brasileiro, especialmente em São Paulo, Rio de Janeiro e Minas Gerais, devido a fatores históricos como a acumulação de capital do café, infraestrutura de transportes e mercado consumidor.',
    componente: 'Geografia',
    tema: 'industrialização brasileira',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08GE13',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-011',
    enunciado: 'Explique as principais causas do desmatamento na Amazônia e seus impactos ambientais e climáticos.',
    tipo: 'dissertativa',
    explicacao: 'Principais causas: expansão da agropecuária (criação de gado e monocultura de soja), extração ilegal de madeira, mineração, queimadas e construção de estradas. Impactos: perda de biodiversidade, alteração do regime de chuvas, aumento das emissões de gases do efeito estufa, degradação do solo, erosão e impacto nas comunidades indígenas e ribeirinhas.',
    componente: 'Geografia',
    tema: 'desmatamento na Amazônia',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07GE11',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-012',
    enunciado: 'Qual das formas de relevo a seguir é predominante no território brasileiro?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Montanhas', 'b) Planaltos e depressões', 'c) Cordilheiras', 'd) Planícies de altitude'],
    resposta_correta: 'b',
    explicacao: 'O relevo brasileiro é predominantemente composto por planaltos e depressões, resultado de um território geologicamente antigo e estável. O Brasil não possui grandes cadeias montanhosas recentes como os Andes.',
    componente: 'Geografia',
    tema: 'relevo brasileiro',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06GE03',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-013',
    enunciado: 'Uma pirâmide etária com base larga e topo estreito indica uma população com:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Alta taxa de natalidade e baixa expectativa de vida', 'b) Baixa taxa de natalidade e alta expectativa de vida', 'c) Crescimento populacional negativo', 'd) Equilíbrio entre jovens e idosos'],
    resposta_correta: 'a',
    explicacao: 'Uma pirâmide etária com base larga indica alta taxa de natalidade (muitos jovens) e topo estreito indica baixa expectativa de vida (poucos idosos), típica de países em desenvolvimento ou subdesenvolvidos.',
    componente: 'Geografia',
    tema: 'pirâmide etária',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08GE04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-014',
    enunciado: 'Qual fonte de energia é considerada renovável e tem crescido significativamente no Brasil, utilizando a força dos ventos?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Energia nuclear', 'b) Energia eólica', 'c) Energia termoelétrica', 'd) Energia geotérmica'],
    resposta_correta: 'b',
    explicacao: 'A energia eólica, gerada pela força dos ventos, é renovável e limpa. O Brasil é um dos maiores produtores mundiais, com destaque para os parques eólicos na região Nordeste (Rio Grande do Norte, Bahia, Ceará).',
    componente: 'Geografia',
    tema: 'fontes de energia',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09GE15',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-015',
    enunciado: 'Identifique e explique três problemas ambientais comuns nas grandes cidades brasileiras e suas possíveis soluções.',
    tipo: 'dissertativa',
    explicacao: '1) Poluição do ar: causada por emissões de veículos e indústrias; solução: incentivo ao transporte público e energias limpas. 2) Enchentes/alagamentos: causados pela impermeabilização do solo e falta de drenagem; solução: criação de áreas permeáveis e manutenção de bueiros. 3) Destinação inadequada de resíduos: acúmulo de lixo em lixões; solução: coleta seletiva, reciclagem e aterros sanitários.',
    componente: 'Geografia',
    tema: 'problemas ambientais urbanos',
    dificuldade: 'medio',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09GE13',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-geo-016',
    enunciado: 'Qual tipo de agricultura é caracterizado pelo uso intensivo de tecnologia, mecanização e produção em larga escala voltada para exportação?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Agricultura de subsistência', 'b) Agricultura familiar', 'c) Agricultura comercial (agronegócio)', 'd) Agricultura orgânica'],
    resposta_correta: 'c',
    explicacao: 'A agricultura comercial (agronegócio) utiliza tecnologia avançada, mecanização, insumos químicos e grandes extensões de terra para produção em larga escala, voltada ao mercado interno e exportação. O Brasil é um dos maiores exportadores de soja, café e carne.',
    componente: 'Geografia',
    tema: 'agricultura brasileira',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07GE06',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-003',
    enunciado: 'Na frase "Os meninos corre no pátio", há um erro de:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Regência verbal', 'b) Concordância verbal', 'c) Pontuação', 'd) Ortografia'],
    resposta_correta: 'b',
    explicacao: 'Há erro de concordância verbal: o sujeito "Os meninos" está no plural, portanto o verbo deve concordar: "Os meninos correm no pátio".',
    componente: 'Língua Portuguesa',
    tema: 'concordância verbal',
    dificuldade: 'facil',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07LP09',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-004',
    enunciado: 'Leia o texto: "A poluição dos rios é um dos maiores problemas ambientais das grandes cidades. Resíduos industriais e esgoto doméstico são despejados sem tratamento." Qual é a ideia principal do texto?',
    tipo: 'multipla_escolha',
    alternativas: ['a) A importância da reciclagem', 'b) A poluição dos rios como grave problema ambiental urbano', 'c) Os benefícios da industrialização', 'd) A construção de novas cidades'],
    resposta_correta: 'b',
    explicacao: 'A ideia principal é que a poluição dos rios constitui um sério problema ambiental nas grandes cidades, causada pelo despejo de resíduos industriais e esgoto sem tratamento.',
    componente: 'Língua Portuguesa',
    tema: 'interpretação de texto',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06LP01',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-005',
    enunciado: 'Na frase "Aquele homem é uma fera nos negócios", a expressão "é uma fera" é um exemplo de:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Comparação', 'b) Metáfora', 'c) Metonímia', 'd) Hipérbole'],
    resposta_correta: 'b',
    explicacao: 'É uma metáfora, pois há uma comparação implícita (sem usar "como") entre o homem e uma fera, atribuindo-lhe qualidades como agressividade e habilidade nos negócios.',
    componente: 'Língua Portuguesa',
    tema: 'figuras de linguagem',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08LP08',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-006',
    enunciado: 'Qual alternativa apresenta o uso CORRETO da regência verbal do verbo "assistir" no sentido de "ver"?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Assisti o filme ontem', 'b) Assisti ao filme ontem', 'c) Assisti no filme ontem', 'd) Assisti pelo filme ontem'],
    resposta_correta: 'b',
    explicacao: 'O verbo "assistir" no sentido de "ver, presenciar" é transitivo indireto e exige a preposição "a": assisti ao filme, assisti à aula, assisti ao jogo.',
    componente: 'Língua Portuguesa',
    tema: 'regência verbal',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09LP04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-007',
    enunciado: 'Explique a diferença entre os gêneros textuais "notícia" e "crônica", identificando características de cada um e dando exemplos de onde são encontrados.',
    tipo: 'dissertativa',
    explicacao: 'Notícia: gênero jornalístico informativo que relata fatos reais de forma objetiva e impessoal, seguindo a estrutura de pirâmide invertida (informações mais importantes primeiro). Encontrada em jornais e portais de notícias. Crônica: gênero literário que parte de fatos do cotidiano para fazer reflexões pessoais, com linguagem mais leve e subjetiva, podendo usar humor ou ironia. Encontrada em jornais, revistas e livros.',
    componente: 'Língua Portuguesa',
    tema: 'gêneros textuais',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06LP01',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-008',
    enunciado: 'Qual das palavras a seguir está grafada CORRETAMENTE?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Previlégio', 'b) Privilégio', 'c) Previlégeo', 'd) Priviégio'],
    resposta_correta: 'b',
    explicacao: 'A grafia correta é "privilégio", com "i" na primeira sílaba. É um erro comum trocar por "previlégio".',
    componente: 'Língua Portuguesa',
    tema: 'ortografia',
    dificuldade: 'facil',
    ano_serie: '6º Ano',
    habilidade_bncc: 'EF06LP06',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-009',
    enunciado: 'Na frase "Maria comprou frutas legumes e verduras no mercado", está faltando o uso adequado de:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Ponto final', 'b) Vírgula para separar itens de uma enumeração', 'c) Ponto e vírgula', 'd) Dois pontos'],
    resposta_correta: 'b',
    explicacao: 'Faltam vírgulas para separar os itens da enumeração: "Maria comprou frutas, legumes e verduras no mercado." A vírgula é usada antes do último item, onde entra o "e".',
    componente: 'Língua Portuguesa',
    tema: 'pontuação',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07LP04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-010',
    enunciado: 'Explique o que é coerência e coesão textual, apresentando a diferença entre os dois conceitos e dando um exemplo de cada.',
    tipo: 'dissertativa',
    explicacao: 'Coerência: refere-se à lógica e ao sentido do texto como um todo, garantindo que as ideias não sejam contraditórias. Exemplo: não faz sentido dizer "Saí sem guarda-chuva porque chovia muito" (incoerente). Coesão: refere-se à articulação entre as partes do texto por meio de conectivos e referências. Exemplo: uso de "portanto", "entretanto", pronomes como "ele/ela" para retomar termos anteriores.',
    componente: 'Língua Portuguesa',
    tema: 'coerência e coesão',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08LP14',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-011',
    enunciado: 'A variação linguística é um fenômeno natural das línguas. Qual alternativa exemplifica uma variação regional (dialetal)?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Usar gírias com amigos', 'b) Falar "aipim" no Sul e "macaxeira" no Nordeste para mandioca', 'c) Usar linguagem formal em uma entrevista de emprego', 'd) Escrever em linguagem técnica em artigos científicos'],
    resposta_correta: 'b',
    explicacao: 'A variação regional (ou diatópica) refere-se às diferenças de vocabulário, pronúncia e expressões entre regiões do país, como chamar "mandioca" de "aipim" (Sul) ou "macaxeira" (Nordeste).',
    componente: 'Língua Portuguesa',
    tema: 'variação linguística',
    dificuldade: 'medio',
    ano_serie: '7º Ano',
    habilidade_bncc: 'EF07LP01',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-012',
    enunciado: 'Na palavra "infelizmente", os elementos mórficos são: in- (prefixo), -feliz- (radical) e -mente (sufixo). Esse processo de formação é chamado de:',
    tipo: 'multipla_escolha',
    alternativas: ['a) Composição por justaposição', 'b) Composição por aglutinação', 'c) Derivação prefixal e sufixal', 'd) Derivação regressiva'],
    resposta_correta: 'c',
    explicacao: 'A palavra "infelizmente" é formada por derivação prefixal e sufixal (parassíntese aparente), pois ao radical "feliz" foram acrescentados o prefixo "in-" e o sufixo "-mente".',
    componente: 'Língua Portuguesa',
    tema: 'formação de palavras',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08LP05',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-013',
    enunciado: 'Identifique e classifique a oração subordinada no período: "Espero que você estude para a prova." Explique sua função sintática.',
    tipo: 'dissertativa',
    explicacao: 'A oração "que você estude para a prova" é uma oração subordinada substantiva objetiva direta, pois exerce a função de objeto direto do verbo "espero" da oração principal. Equivale a "Espero isso" (isso = que você estude para a prova).',
    componente: 'Língua Portuguesa',
    tema: 'orações subordinadas',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09LP08',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-014',
    enunciado: 'Em qual das frases a seguir o uso da crase está CORRETO?',
    tipo: 'multipla_escolha',
    alternativas: ['a) Fui à pé para a escola', 'b) Entreguei o livro à professora', 'c) Refiro-me à ele', 'd) Chegamos à São Paulo'],
    resposta_correta: 'b',
    explicacao: 'A crase está correta em "Entreguei o livro à professora" pois há fusão da preposição "a" (exigida por "entreguei a") com o artigo "a" (antes de "professora"). Não se usa crase antes de palavras masculinas, pronomes pessoais ou a maioria dos nomes de cidades.',
    componente: 'Língua Portuguesa',
    tema: 'crase',
    dificuldade: 'dificil',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09LP04',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-015',
    enunciado: 'Transforme a frase da voz ativa para a voz passiva: "O aluno resolveu o exercício."',
    tipo: 'multipla_escolha',
    alternativas: ['a) O exercício resolveu o aluno', 'b) O exercício foi resolvido pelo aluno', 'c) Resolveu-se o aluno', 'd) O aluno foi resolvido pelo exercício'],
    resposta_correta: 'b',
    explicacao: 'Na voz passiva analítica, o objeto direto vira sujeito paciente: "O exercício (sujeito paciente) foi resolvido (locução verbal passiva) pelo aluno (agente da passiva)."',
    componente: 'Língua Portuguesa',
    tema: 'vozes verbais',
    dificuldade: 'medio',
    ano_serie: '8º Ano',
    habilidade_bncc: 'EF08LP08',
    fonte: 'Banco de Questões Ponto School',
  },
  {
    id: 'q-lp-016',
    enunciado: 'Explique o que é intertextualidade e dê um exemplo de como um texto pode fazer referência a outro, identificando o tipo de relação intertextual.',
    tipo: 'dissertativa',
    explicacao: 'Intertextualidade é a relação de diálogo entre textos, quando um texto faz referência a outro. Exemplo: a música "Monte Castelo" de Renato Russo utiliza versos do Soneto 11 de Camões e trechos da Epístola de São Paulo, configurando uma citação/alusão. Tipos: citação (reprodução direta), paráfrase (reescrita com mesma ideia), paródia (imitação com tom humorístico/crítico) e alusão (referência indireta).',
    componente: 'Língua Portuguesa',
    tema: 'intertextualidade',
    dificuldade: 'medio',
    ano_serie: '9º Ano',
    habilidade_bncc: 'EF09LP03',
    fonte: 'Banco de Questões Ponto School',
  },
];

export async function pesquisarBancoQuestoesV2(
  input: CapabilityInput
): Promise<CapabilityOutput> {
  const debug_log: DebugEntry[] = [];
  const startTime = Date.now();
  const params = (input.context || {}) as PesquisarBancoQuestoesParams;
  const maxResults = params.max_resultados || 10;

  if (!params.componente && params.disciplina_extraida) {
    params.componente = params.disciplina_extraida;
    console.log(`📝 [pesquisar_banco_questoes] Usando disciplina_extraida como componente: "${params.componente}"`);
  }
  if (!params.ano_serie && params.turma_extraida) {
    params.ano_serie = params.turma_extraida;
    console.log(`📝 [pesquisar_banco_questoes] Usando turma_extraida como ano_serie: "${params.ano_serie}"`);
  }
  if (!params.tema && params.tema_limpo) {
    params.tema = params.tema_limpo;
    console.log(`📝 [pesquisar_banco_questoes] Usando tema_limpo como tema: "${params.tema}"`);
  }

  try {
    debug_log.push({
      timestamp: new Date().toISOString(),
      type: 'action',
      narrative: '📝 ETAPA 1: Iniciando pesquisa no Banco de Questões de Referência...',
      technical_data: {
        componente: params.componente || 'todos',
        ano_serie: params.ano_serie || 'todos',
        tema: params.tema || 'livre',
        dificuldade: params.dificuldade || 'todas',
        tipo_questao: params.tipo_questao || 'todos',
        max_resultados: maxResults,
      },
    });

    let resultados = [...BANCO_QUESTOES];

    if (params.componente) {
      const compLower = params.componente.toLowerCase().trim();
      const compAliases: Record<string, string> = {
        'matematica': 'Matemática', 'matemática': 'Matemática', 'mat': 'Matemática',
        'lingua portuguesa': 'Língua Portuguesa', 'língua portuguesa': 'Língua Portuguesa',
        'portugues': 'Língua Portuguesa', 'português': 'Língua Portuguesa', 'lp': 'Língua Portuguesa',
        'ciencias': 'Ciências', 'ciências': 'Ciências', 'cie': 'Ciências',
        'historia': 'História', 'história': 'História', 'hist': 'História',
        'geografia': 'Geografia', 'geo': 'Geografia',
      };
      const normalized = compAliases[compLower] || params.componente;
      resultados = resultados.filter(q => q.componente.toLowerCase() === normalized.toLowerCase());

      debug_log.push({
        timestamp: new Date().toISOString(),
        type: 'action',
        narrative: `🔍 ETAPA 2: Filtro por componente "${normalized}" → ${resultados.length} questão(ões)`,
        technical_data: { filtro: 'componente', valor: normalized, restantes: resultados.length },
      });
    }

    if (params.ano_serie) {
      const anoLower = params.ano_serie.toLowerCase();
      const beforeCount = resultados.length;
      resultados = resultados.filter(q => {
        const qAnoLower = q.ano_serie.toLowerCase();
        return qAnoLower.includes(anoLower) || anoLower.includes(qAnoLower);
      });

      debug_log.push({
        timestamp: new Date().toISOString(),
        type: 'action',
        narrative: `🔍 Filtro por ano/série "${params.ano_serie}" → ${beforeCount} → ${resultados.length} questão(ões)`,
        technical_data: { filtro: 'ano_serie', valor: params.ano_serie, antes: beforeCount, depois: resultados.length },
      });
    }

    if (params.tema && params.tema.trim().length > 0) {
      const temaLower = params.tema.toLowerCase();
      const beforeCount = resultados.length;
      const scored = resultados.map(q => {
        let score = 0;
        if (q.tema.toLowerCase().includes(temaLower)) score += 3;
        if (q.enunciado.toLowerCase().includes(temaLower)) score += 2;
        if (q.explicacao.toLowerCase().includes(temaLower)) score += 1;
        const temaWords = temaLower.split(/\s+/);
        for (const word of temaWords) {
          if (word.length > 3) {
            if (q.tema.toLowerCase().includes(word)) score += 1;
            if (q.enunciado.toLowerCase().includes(word)) score += 0.5;
          }
        }
        return { questao: q, score };
      }).filter(s => s.score > 0).sort((a, b) => b.score - a.score);

      resultados = scored.map(s => s.questao);

      debug_log.push({
        timestamp: new Date().toISOString(),
        type: 'action',
        narrative: `🔎 Filtro por tema "${params.tema}" → ${beforeCount} → ${resultados.length} questão(ões) relevantes`,
        technical_data: { filtro: 'tema', valor: params.tema, antes: beforeCount, depois: resultados.length },
      });
    }

    if (params.dificuldade) {
      const beforeCount = resultados.length;
      resultados = resultados.filter(q => q.dificuldade === params.dificuldade);

      debug_log.push({
        timestamp: new Date().toISOString(),
        type: 'action',
        narrative: `📊 Filtro por dificuldade "${params.dificuldade}" → ${beforeCount} → ${resultados.length} questão(ões)`,
        technical_data: { filtro: 'dificuldade', valor: params.dificuldade, antes: beforeCount, depois: resultados.length },
      });
    }

    if (params.tipo_questao && params.tipo_questao !== 'todos') {
      const beforeCount = resultados.length;
      resultados = resultados.filter(q => q.tipo === params.tipo_questao);

      debug_log.push({
        timestamp: new Date().toISOString(),
        type: 'action',
        narrative: `📋 Filtro por tipo "${params.tipo_questao}" → ${beforeCount} → ${resultados.length} questão(ões)`,
        technical_data: { filtro: 'tipo_questao', valor: params.tipo_questao, antes: beforeCount, depois: resultados.length },
      });
    }

    resultados = resultados.slice(0, maxResults);

    const componentesEncontrados = [...new Set(resultados.map(q => q.componente))];
    const temasEncontrados = [...new Set(resultados.map(q => q.tema))];
    const dificuldades = [...new Set(resultados.map(q => q.dificuldade))];

    debug_log.push({
      timestamp: new Date().toISOString(),
      type: 'discovery',
      narrative: `📋 RESULTADO: Encontradas ${resultados.length} questão(ões) de referência de ${componentesEncontrados.length} componente(s) sobre ${temasEncontrados.length} tema(s)`,
      technical_data: {
        total_encontrado: resultados.length,
        componentes: componentesEncontrados,
        temas: temasEncontrados,
        dificuldades,
        questoes: resultados.map(q => ({
          id: q.id,
          tipo: q.tipo,
          componente: q.componente,
          tema: q.tema,
          dificuldade: q.dificuldade,
        })),
      },
    });

    const elapsedTime = Date.now() - startTime;

    const dataConfirmation = createDataConfirmation([
      createDataCheck('banco_loaded', 'Banco de questões carregado', BANCO_QUESTOES.length > 0, BANCO_QUESTOES.length, '> 0 questões'),
      createDataCheck('results_found', 'Questões encontradas', resultados.length > 0, resultados.length, '> 0'),
      createDataCheck('has_explanations', 'Questões com explicação', resultados.every(q => q.explicacao && q.explicacao.length > 0), resultados.length, 'todas com explicação'),
    ]);

    debug_log.push({
      timestamp: new Date().toISOString(),
      type: 'confirmation',
      narrative: `✅ Pesquisa no Banco de Questões concluída em ${elapsedTime}ms — ${resultados.length} questão(ões) de referência encontrada(s)`,
      technical_data: {
        duracao_ms: elapsedTime,
        total_resultados: resultados.length,
        resumo: dataConfirmation.summary,
      },
    });

    const formattedForPrompt = formatQuestoesForPrompt(resultados);

    return {
      success: true,
      capability_id: 'pesquisar_banco_questoes',
      execution_id: input.execution_id,
      timestamp: new Date().toISOString(),
      data: {
        questoes: resultados,
        count: resultados.length,
        componentes: componentesEncontrados,
        temas: temasEncontrados,
        dificuldades,
        prompt_context: formattedForPrompt,
        summary: `Encontradas ${resultados.length} questão(ões) de referência${params.componente ? ` de ${params.componente}` : ''}${params.tema ? ` sobre ${params.tema}` : ''}`,
      },
      error: null,
      debug_log,
      data_confirmation: dataConfirmation,
      metadata: {
        duration_ms: elapsedTime,
        retry_count: 0,
        data_source: 'Banco de Questões Ponto School (banco-questoes-referencia)',
      },
    };
  } catch (error) {
    const elapsedTime = Date.now() - startTime;
    const errorMessage = error instanceof Error ? error.message : String(error);

    debug_log.push({
      timestamp: new Date().toISOString(),
      type: 'error',
      narrative: `❌ ERRO: Falha na pesquisa no Banco de Questões — ${errorMessage}`,
      technical_data: {
        error: errorMessage,
        stack: error instanceof Error ? error.stack : undefined,
        duration_ms: elapsedTime,
      },
    });

    console.error('❌ [Capability:PESQUISAR_BANCO_QUESTOES] ERRO:', errorMessage);

    return {
      success: false,
      capability_id: 'pesquisar_banco_questoes',
      execution_id: input.execution_id,
      timestamp: new Date().toISOString(),
      data: null,
      error: {
        code: 'BANCO_QUESTOES_SEARCH_FAILED',
        message: errorMessage,
        severity: 'medium',
        recoverable: true,
        recovery_suggestion: 'Verifique os parâmetros de busca (componente, tema, dificuldade) e tente novamente',
      },
      debug_log,
      metadata: {
        duration_ms: elapsedTime,
        retry_count: 0,
        data_source: 'Banco de Questões Ponto School',
      },
    };
  }
}

function formatQuestoesForPrompt(questoes: QuestaoReferencia[]): string {
  if (questoes.length === 0) {
    return 'Nenhuma questão de referência encontrada para os filtros especificados.';
  }

  const parts: string[] = ['QUESTÕES DE REFERÊNCIA ENCONTRADAS (use como modelo de qualidade e estilo):'];

  for (const q of questoes) {
    parts.push(`\n📝 [${q.componente} | ${q.tema} | ${q.dificuldade}]`);
    parts.push(`   Enunciado: ${q.enunciado}`);
    if (q.alternativas && q.alternativas.length > 0) {
      parts.push(`   Alternativas: ${q.alternativas.join(' | ')}`);
      parts.push(`   Resposta: ${q.resposta_correta}`);
    }
    parts.push(`   Explicação: ${q.explicacao}`);
    if (q.habilidade_bncc) {
      parts.push(`   BNCC: ${q.habilidade_bncc}`);
    }
  }

  parts.push('\n⚠️ IMPORTANTE: Use estas questões como REFERÊNCIA de qualidade e estilo. NÃO copie literalmente — crie questões ORIGINAIS inspiradas neste padrão.');

  return parts.join('\n');
}
