export const ENSINO_RELIGIOSO_HABILIDADES: Record<string, Array<{ codigo: string; descricao: string; objetoConhecimento: string }>> = {
  '1º Ano': [
    { codigo: 'EF01ER01', descricao: 'Identificar e acolher as semelhanças e diferenças entre o eu, o outro e o nós.', objetoConhecimento: 'O eu, o outro e o nós' },
    { codigo: 'EF01ER02', descricao: 'Reconhecer que o seu nome e o das demais pessoas os identificam e os diferenciam.', objetoConhecimento: 'O eu, o outro e o nós' },
    { codigo: 'EF01ER03', descricao: 'Reconhecer e respeitar as características físicas e subjetivas de cada um.', objetoConhecimento: 'Imanência e transcendência' },
    { codigo: 'EF01ER04', descricao: 'Valorizar a diversidade de formas de vida.', objetoConhecimento: 'Imanência e transcendência' },
    { codigo: 'EF01ER05', descricao: 'Identificar e acolher sentimentos, lembranças, memórias e saberes de cada um.', objetoConhecimento: 'Sentimentos, lembranças, memórias e saberes' },
    { codigo: 'EF01ER06', descricao: 'Identificar as diferentes formas pelas quais as pessoas manifestam sentimentos, ideias, memórias, gostos e crenças em diferentes espaços.', objetoConhecimento: 'Sentimentos, lembranças, memórias e saberes' },
  ],
  '2º Ano': [
    { codigo: 'EF02ER01', descricao: 'Reconhecer os diferentes espaços e tempos do vivido, do celebrado e do convivido.', objetoConhecimento: 'Espaços e tempos religiosos' },
    { codigo: 'EF02ER02', descricao: 'Identificar os diferentes papéis desempenhados pelas pessoas nas celebrações e rituais religiosos.', objetoConhecimento: 'Papéis e funções religiosas' },
    { codigo: 'EF02ER03', descricao: 'Caracterizar os símbolos religiosos presentes nos diferentes espaços de convivência.', objetoConhecimento: 'Símbolos religiosos' },
    { codigo: 'EF02ER04', descricao: 'Reconhecer a importância dos símbolos religiosos para as diferentes tradições.', objetoConhecimento: 'Símbolos religiosos' },
    { codigo: 'EF02ER05', descricao: 'Identificar e valorizar as diferentes formas de expressão religiosa (cantos, danças, orações, rituais).', objetoConhecimento: 'Expressões religiosas' },
    { codigo: 'EF02ER06', descricao: 'Reconhecer a importância das expressões religiosas para a vida das pessoas.', objetoConhecimento: 'Expressões religiosas' },
    { codigo: 'EF02ER07', descricao: 'Identificar e acolher as diferentes formas de manifestação da espiritualidade.', objetoConhecimento: 'Espiritualidade' },
  ],
  '3º Ano': [
    { codigo: 'EF03ER01', descricao: 'Identificar e descrever as diferentes manifestações religiosas presentes em seu contexto.', objetoConhecimento: 'Manifestações religiosas' },
    { codigo: 'EF03ER02', descricao: 'Reconhecer a importância das manifestações religiosas para a cultura e a história dos povos.', objetoConhecimento: 'Cultura e história religiosa' },
    { codigo: 'EF03ER03', descricao: 'Caracterizar os ritos e rituais religiosos presentes nas diferentes tradições.', objetoConhecimento: 'Ritos e rituais religiosos' },
    { codigo: 'EF03ER04', descricao: 'Reconhecer a importância dos ritos e rituais religiosos para a vida das pessoas.', objetoConhecimento: 'Ritos e rituais religiosos' },
    { codigo: 'EF03ER05', descricao: 'Identificar e valorizar as diferentes formas de celebrar o sagrado.', objetoConhecimento: 'Celebrações religiosas' },
    { codigo: 'EF03ER06', descricao: 'Reconhecer a importância das celebrações religiosas para a vida das pessoas.', objetoConhecimento: 'Celebrações religiosas' },
    { codigo: 'EF03ER07', descricao: 'Identificar e acolher as diferentes formas de manifestação da fé.', objetoConhecimento: 'Fé' },
  ],
  '4º Ano': [
    { codigo: 'EF04ER01', descricao: 'Identificar e descrever as diferentes crenças e convicções religiosas presentes em seu contexto.', objetoConhecimento: 'Crenças e convicções religiosas' },
    { codigo: 'EF04ER02', descricao: 'Reconhecer a importância das crenças e convicções religiosas para a vida das pessoas.', objetoConhecimento: 'Crenças e convicções religiosas' },
    { codigo: 'EF04ER03', descricao: 'Caracterizar os mitos e narrativas religiosas presentes nas diferentes tradições.', objetoConhecimento: 'Mitos e narrativas religiosas' },
    { codigo: 'EF04ER04', descricao: 'Reconhecer a importância dos mitos e narrativas religiosas para a cultura e a história dos povos.', objetoConhecimento: 'Mitos e narrativas religiosas' },
    { codigo: 'EF04ER05', descricao: 'Identificar e valorizar as diferentes formas de expressar a religiosidade.', objetoConhecimento: 'Expressões de religiosidade' },
    { codigo: 'EF04ER06', descricao: 'Reconhecer a importância das expressões de religiosidade para a vida das pessoas.', objetoConhecimento: 'Expressões de religiosidade' },
    { codigo: 'EF04ER07', descricao: 'Identificar e acolher as diferentes formas de manifestação da religiosidade.', objetoConhecimento: 'Religiosidade' },
  ],
  '5º Ano': [
    { codigo: 'EF05ER01', descricao: 'Identificar e descrever as diferentes tradições religiosas presentes em seu contexto.', objetoConhecimento: 'Tradições religiosas' },
    { codigo: 'EF05ER02', descricao: 'Reconhecer a importância das tradições religiosas para a cultura e a história dos povos.', objetoConhecimento: 'Cultura e história religiosa' },
    { codigo: 'EF05ER03', descricao: 'Caracterizar os textos sagrados presentes nas diferentes tradições religiosas.', objetoConhecimento: 'Textos sagrados' },
    { codigo: 'EF05ER04', descricao: 'Reconhecer a importância dos textos sagrados para a vida das pessoas.', objetoConhecimento: 'Textos sagrados' },
    { codigo: 'EF05ER05', descricao: 'Identificar e valorizar as diferentes formas de interpretar os textos sagrados.', objetoConhecimento: 'Interpretação de textos sagrados' },
    { codigo: 'EF05ER06', descricao: 'Reconhecer a importância da interpretação dos textos sagrados para a vida das pessoas.', objetoConhecimento: 'Interpretação de textos sagrados' },
    { codigo: 'EF05ER07', descricao: 'Identificar e acolher as diferentes formas de manifestação da transcendência.', objetoConhecimento: 'Transcendência' },
  ],
  '6º Ano': [
    { codigo: 'EF06ER01', descricao: 'Reconhecer o papel da tradição na transmissão de conhecimentos e valores.', objetoConhecimento: 'Tradição' },
    { codigo: 'EF06ER02', descricao: 'Identificar e descrever as diferentes formas de expressão da espiritualidade.', objetoConhecimento: 'Espiritualidade' },
    { codigo: 'EF06ER03', descricao: 'Analisar a relação entre espiritualidade e a busca por sentido da vida.', objetoConhecimento: 'Sentido da vida' },
    { codigo: 'EF06ER04', descricao: 'Reconhecer a importância do diálogo inter-religioso para a construção de uma sociedade justa e pacífica.', objetoConhecimento: 'Diálogo inter-religioso' },
    { codigo: 'EF06ER05', descricao: 'Identificar e valorizar as diferentes formas de manifestação do sagrado.', objetoConhecimento: 'Sagrado' },
    { codigo: 'EF06ER06', descricao: 'Reconhecer a importância do sagrado para a vida das pessoas.', objetoConhecimento: 'Sagrado' },
  ],
  '7º Ano': [
    { codigo: 'EF07ER01', descricao: 'Reconhecer o papel da ética na relação com o outro e com o transcendente.', objetoConhecimento: 'Ética' },
    { codigo: 'EF07ER02', descricao: 'Identificar e descrever as diferentes concepções de bem e mal nas tradições religiosas.', objetoConhecimento: 'Bem e mal' },
    { codigo: 'EF07ER03', descricao: 'Analisar a relação entre ética e moral nas tradições religiosas.', objetoConhecimento: 'Ética e moral' },
    { codigo: 'EF07ER04', descricao: 'Reconhecer a importância do respeito à diversidade religiosa para a construção de uma sociedade justa e pacífica.', objetoConhecimento: 'Diversidade religiosa' },
    { codigo: 'EF07ER05', descricao: 'Identificar e valorizar as diferentes formas de manifestação da justiça.', objetoConhecimento: 'Justiça' },
    { codigo: 'EF07ER06', descricao: 'Reconhecer a importância da justiça para a vida das pessoas.', objetoConhecimento: 'Justiça' },
  ],
  '8º Ano': [
    { codigo: 'EF08ER01', descricao: 'Reconhecer o papel da liberdade na relação com o outro e com o transcendente.', objetoConhecimento: 'Liberdade' },
    { codigo: 'EF08ER02', descricao: 'Identificar e descrever as diferentes concepções de liberdade nas tradições religiosas.', objetoConhecimento: 'Liberdade' },
    { codigo: 'EF08ER03', descricao: 'Analisar a relação entre liberdade e responsabilidade nas tradições religiosas.', objetoConhecimento: 'Liberdade e responsabilidade' },
    { codigo: 'EF08ER04', descricao: 'Reconhecer a importância do respeito à liberdade religiosa para a construção de uma sociedade justa e pacífica.', objetoConhecimento: 'Liberdade religiosa' },
    { codigo: 'EF08ER05', descricao: 'Identificar e valorizar as diferentes formas de manifestação da paz.', objetoConhecimento: 'Paz' },
    { codigo: 'EF08ER06', descricao: 'Reconhecer a importância da paz para a vida das pessoas.', objetoConhecimento: 'Paz' },
    { codigo: 'EF08ER07', descricao: 'Identificar e acolher as diferentes formas de manifestação da esperança.', objetoConhecimento: 'Esperança' },
    { codigo: 'EF08ER08', descricao: 'Reconhecer a importância da esperança para a vida das pessoas.', objetoConhecimento: 'Esperança' },
  ],
  '9º Ano': [
    { codigo: 'EF09ER01', descricao: 'Reconhecer o papel da alteridade na relação com o outro e com o transcendente.', objetoConhecimento: 'Alteridade' },
    { codigo: 'EF09ER02', descricao: 'Identificar e descrever as diferentes concepções de alteridade nas tradições religiosas.', objetoConhecimento: 'Alteridade' },
    { codigo: 'EF09ER03', descricao: 'Analisar a relação entre alteridade e diálogo nas tradições religiosas.', objetoConhecimento: 'Alteridade e diálogo' },
    { codigo: 'EF09ER04', descricao: 'Reconhecer a importância do diálogo inter-religioso para a construção de uma sociedade justa e pacífica.', objetoConhecimento: 'Diálogo inter-religioso' },
    { codigo: 'EF09ER05', descricao: 'Identificar e valorizar as diferentes formas de manifestação do amor.', objetoConhecimento: 'Amor' },
    { codigo: 'EF09ER06', descricao: 'Reconhecer a importância do amor para a vida das pessoas.', objetoConhecimento: 'Amor' },
    { codigo: 'EF09ER07', descricao: 'Identificar e acolher as diferentes formas de manifestação da solidariedade.', objetoConhecimento: 'Solidariedade' },
    { codigo: 'EF09ER08', descricao: 'Reconhecer a importância da solidariedade para a vida das pessoas.', objetoConhecimento: 'Solidariedade' },
  ],
};
