export const LINGUA_INGLESA_HABILIDADES: Record<string, Array<{ codigo: string; descricao: string; objetoConhecimento: string }>> = {
  '6º Ano': [
    { codigo: 'EF06LI01', descricao: 'Interagir em situações de intercâmbio oral, com autonomia, para expressar ideias, informações e sentimentos em língua inglesa.', objetoConhecimento: 'Interação oral' },
    { codigo: 'EF06LI02', descricao: 'Produzir textos orais e escritos em língua inglesa, com autonomia, para expressar ideias, informações e sentimentos.', objetoConhecimento: 'Produção oral e escrita' },
    { codigo: 'EF06LI03', descricao: 'Compreender textos orais e escritos em língua inglesa, com autonomia, para identificar informações gerais e específicas.', objetoConhecimento: 'Compreensão oral e escrita' },
    { codigo: 'EF06LI04', descricao: 'Utilizar estratégias de leitura (scanning, skimming, inferência) para compreender textos em língua inglesa.', objetoConhecimento: 'Estratégias de leitura' },
    { codigo: 'EF06LI05', descricao: 'Utilizar estratégias de escrita (planejamento, rascunho, revisão, edição) para produzir textos em língua inglesa.', objetoConhecimento: 'Estratégias de escrita' },
    { codigo: 'EF06LI06', descricao: 'Reconhecer e utilizar vocabulário básico em língua inglesa relacionado a temas do cotidiano.', objetoConhecimento: 'Vocabulário' },
    { codigo: 'EF06LI07', descricao: 'Reconhecer e utilizar estruturas gramaticais básicas em língua inglesa (presente simples, presente contínuo, passado simples).', objetoConhecimento: 'Gramática' },
    { codigo: 'EF06LI08', descricao: 'Identificar e utilizar diferentes gêneros textuais em língua inglesa (cartas, e-mails, mensagens, histórias em quadrinhos).', objetoConhecimento: 'Gêneros textuais' },
    { codigo: 'EF06LI09', descricao: 'Valorizar a diversidade cultural presente na língua inglesa e em países de língua inglesa.', objetoConhecimento: 'Diversidade cultural' },
    { codigo: 'EF06LI10', descricao: 'Utilizar recursos tecnológicos (dicionários online, tradutores, aplicativos) para auxiliar na aprendizagem de língua inglesa.', objetoConhecimento: 'Recursos tecnológicos' },
    { codigo: 'EF06LI11', descricao: 'Participar de atividades lúdicas e jogos em língua inglesa para desenvolver a fluência e a confiança na comunicação.', objetoConhecimento: 'Atividades lúdicas' },
    { codigo: 'EF06LI12', descricao: 'Expressar opiniões e ideias em língua inglesa sobre temas do cotidiano.', objetoConhecimento: 'Expressão de opiniões' },
    { codigo: 'EF06LI13', descricao: 'Apresentar informações sobre si mesmo e sobre outras pessoas em língua inglesa.', objetoConhecimento: 'Apresentação pessoal' },
    { codigo: 'EF06LI14', descricao: 'Descrever objetos, lugares e pessoas em língua inglesa.', objetoConhecimento: 'Descrição' },
    { codigo: 'EF06LI15', descricao: 'Narrar eventos e experiências em língua inglesa.', objetoConhecimento: 'Narração' },
    { codigo: 'EF06LI16', descricao: 'Fazer e responder perguntas em língua inglesa sobre temas do cotidiano.', objetoConhecimento: 'Perguntas e respostas' },
    { codigo: 'EF06LI17', descricao: 'Dar e seguir instruções em língua inglesa.', objetoConhecimento: 'Instruções' },
    { codigo: 'EF06LI18', descricao: 'Expressar gostos e preferências em língua inglesa.', objetoConhecimento: 'Gostos e preferências' },
    { codigo: 'EF06LI19', descricao: 'Fazer convites e aceitar/recusar em língua inglesa.', objetoConhecimento: 'Convites' },
    { codigo: 'EF06LI20', descricao: 'Fazer pedidos e oferecer ajuda em língua inglesa.', objetoConhecimento: 'Pedidos e ofertas' },
    { codigo: 'EF06LI21', descricao: 'Expressar agradecimento e desculpas em língua inglesa.', objetoConhecimento: 'Agradecimento e desculpas' },
    { codigo: 'EF06LI22', descricao: 'Expressar sentimentos e emoções em língua inglesa.', objetoConhecimento: 'Sentimentos e emoções' },
    { codigo: 'EF06LI23', descricao: 'Identificar e utilizar expressões idiomáticas básicas em língua inglesa.', objetoConhecimento: 'Expressões idiomáticas' },
    { codigo: 'EF06LI24', descricao: 'Reconhecer e utilizar a pronúncia correta de palavras em língua inglesa.', objetoConhecimento: 'Pronúncia' },
    { codigo: 'EF06LI25', descricao: 'Utilizar a entonação adequada em língua inglesa para expressar diferentes intenções comunicativas.', objetoConhecimento: 'Entonação' },
    { codigo: 'EF06LI26', descricao: 'Participar de conversas informais em língua inglesa sobre temas do cotidiano.', objetoConhecimento: 'Conversação informal' },
  ],
  '7º Ano': [
    { codigo: 'EF07LI01', descricao: 'Interagir em situações de intercâmbio oral, com autonomia, para expressar ideias, informações e sentimentos em língua inglesa.', objetoConhecimento: 'Interação oral' },
    { codigo: 'EF07LI02', descricao: 'Produzir textos orais e escritos em língua inglesa, com autonomia, para expressar ideias, informações e sentimentos.', objetoConhecimento: 'Produção oral e escrita' },
    { codigo: 'EF07LI03', descricao: 'Compreender textos orais e escritos em língua inglesa, com autonomia, para identificar informações gerais e específicas.', objetoConhecimento: 'Compreensão oral e escrita' },
    { codigo: 'EF07LI04', descricao: 'Utilizar estratégias de leitura (scanning, skimming, inferência) para compreender textos em língua inglesa.', objetoConhecimento: 'Estratégias de leitura' },
    { codigo: 'EF07LI05', descricao: 'Utilizar estratégias de escrita (planejamento, rascunho, revisão, edição) para produzir textos em língua inglesa.', objetoConhecimento: 'Estratégias de escrita' },
    { codigo: 'EF07LI06', descricao: 'Reconhecer e utilizar vocabulário em língua inglesa relacionado a temas do cotidiano e de interesse pessoal.', objetoConhecimento: 'Vocabulário' },
    { codigo: 'EF07LI07', descricao: 'Reconhecer e utilizar estruturas gramaticais em língua inglesa (presente perfeito, futuro simples, modais).', objetoConhecimento: 'Gramática' },
    { codigo: 'EF07LI08', descricao: 'Identificar e utilizar diferentes gêneros textuais em língua inglesa (notícias, artigos, resenhas, blogs).', objetoConhecimento: 'Gêneros textuais' },
    { codigo: 'EF07LI09', descricao: 'Valorizar a diversidade cultural presente na língua inglesa e em países de língua inglesa.', objetoConhecimento: 'Diversidade cultural' },
    { codigo: 'EF07LI10', descricao: 'Utilizar recursos tecnológicos (dicionários online, tradutores, aplicativos) para auxiliar na aprendizagem de língua inglesa.', objetoConhecimento: 'Recursos tecnológicos' },
    { codigo: 'EF07LI11', descricao: 'Participar de atividades lúdicas e jogos em língua inglesa para desenvolver a fluência e a confiança na comunicação.', objetoConhecimento: 'Atividades lúdicas' },
    { codigo: 'EF07LI12', descricao: 'Expressar opiniões e ideias em língua inglesa sobre temas do cotidiano e de interesse pessoal.', objetoConhecimento: 'Expressão de opiniões' },
    { codigo: 'EF07LI13', descricao: 'Apresentar informações sobre si mesmo e sobre outras pessoas em língua inglesa.', objetoConhecimento: 'Apresentação pessoal' },
    { codigo: 'EF07LI14', descricao: 'Descrever objetos, lugares e pessoas em língua inglesa.', objetoConhecimento: 'Descrição' },
    { codigo: 'EF07LI15', descricao: 'Narrar eventos e experiências em língua inglesa.', objetoConhecimento: 'Narração' },
    { codigo: 'EF07LI16', descricao: 'Fazer e responder perguntas em língua inglesa sobre temas do cotidiano e de interesse pessoal.', objetoConhecimento: 'Perguntas e respostas' },
    { codigo: 'EF07LI17', descricao: 'Dar e seguir instruções em língua inglesa.', objetoConhecimento: 'Instruções' },
    { codigo: 'EF07LI18', descricao: 'Expressar gostos e preferências em língua inglesa.', objetoConhecimento: 'Gostos e preferências' },
    { codigo: 'EF07LI19', descricao: 'Fazer convites e aceitar/recusar em língua inglesa.', objetoConhecimento: 'Convites' },
    { codigo: 'EF07LI20', descricao: 'Fazer pedidos e oferecer ajuda em língua inglesa.', objetoConhecimento: 'Pedidos e ofertas' },
    { codigo: 'EF07LI21', descricao: 'Expressar agradecimento e desculpas em língua inglesa.', objetoConhecimento: 'Agradecimento e desculpas' },
    { codigo: 'EF07LI22', descricao: 'Expressar sentimentos e emoções em língua inglesa.', objetoConhecimento: 'Sentimentos e emoções' },
  ],
  '8º Ano': [
    { codigo: 'EF08LI01', descricao: 'Interagir em situações de intercâmbio oral, com autonomia, para expressar ideias, informações e sentimentos em língua inglesa.', objetoConhecimento: 'Interação oral' },
    { codigo: 'EF08LI02', descricao: 'Produzir textos orais e escritos em língua inglesa, com autonomia, para expressar ideias, informações e sentimentos.', objetoConhecimento: 'Produção oral e escrita' },
    { codigo: 'EF08LI03', descricao: 'Compreender textos orais e escritos em língua inglesa, com autonomia, para identificar informações gerais e específicas.', objetoConhecimento: 'Compreensão oral e escrita' },
    { codigo: 'EF08LI04', descricao: 'Utilizar estratégias de leitura (scanning, skimming, inferência) para compreender textos em língua inglesa.', objetoConhecimento: 'Estratégias de leitura' },
    { codigo: 'EF08LI05', descricao: 'Utilizar estratégias de escrita (planejamento, rascunho, revisão, edição) para produzir textos em língua inglesa.', objetoConhecimento: 'Estratégias de escrita' },
    { codigo: 'EF08LI06', descricao: 'Reconhecer e utilizar vocabulário em língua inglesa relacionado a temas do cotidiano, de interesse pessoal e de relevância social.', objetoConhecimento: 'Vocabulário' },
    { codigo: 'EF08LI07', descricao: 'Reconhecer e utilizar estruturas gramaticais em língua inglesa (voz passiva, reported speech, condicionais).', objetoConhecimento: 'Gramática' },
    { codigo: 'EF08LI08', descricao: 'Identificar e utilizar diferentes gêneros textuais em língua inglesa (notícias, artigos, resenhas, blogs, posts em redes sociais).', objetoConhecimento: 'Gêneros textuais' },
    { codigo: 'EF08LI09', descricao: 'Valorizar a diversidade cultural presente na língua inglesa e em países de língua inglesa.', objetoConhecimento: 'Diversidade cultural' },
    { codigo: 'EF08LI10', descricao: 'Utilizar recursos tecnológicos (dicionários online, tradutores, aplicativos) para auxiliar na aprendizagem de língua inglesa.', objetoConhecimento: 'Recursos tecnológicos' },
    { codigo: 'EF08LI11', descricao: 'Participar de atividades lúdicas e jogos em língua inglesa para desenvolver a fluência e a confiança na comunicação.', objetoConhecimento: 'Atividades lúdicas' },
    { codigo: 'EF08LI12', descricao: 'Expressar opiniões e ideias em língua inglesa sobre temas do cotidiano, de interesse pessoal e de relevância social.', objetoConhecimento: 'Expressão de opiniões' },
    { codigo: 'EF08LI13', descricao: 'Apresentar informações sobre si mesmo e sobre outras pessoas em língua inglesa.', objetoConhecimento: 'Apresentação pessoal' },
    { codigo: 'EF08LI14', descricao: 'Descrever objetos, lugares e pessoas em língua inglesa.', objetoConhecimento: 'Descrição' },
    { codigo: 'EF08LI15', descricao: 'Narrar eventos e experiências em língua inglesa.', objetoConhecimento: 'Narração' },
    { codigo: 'EF08LI16', descricao: 'Fazer e responder perguntas em língua inglesa sobre temas do cotidiano, de interesse pessoal e de relevância social.', objetoConhecimento: 'Perguntas e respostas' },
    { codigo: 'EF08LI17', descricao: 'Dar e seguir instruções em língua inglesa.', objetoConhecimento: 'Instruções' },
    { codigo: 'EF08LI18', descricao: 'Expressar gostos e preferências em língua inglesa.', objetoConhecimento: 'Gostos e preferências' },
    { codigo: 'EF08LI19', descricao: 'Fazer convites e aceitar/recusar em língua inglesa.', objetoConhecimento: 'Convites' },
  ],
  '9º Ano': [
    { codigo: 'EF09LI01', descricao: 'Interagir em situações de intercâmbio oral, com autonomia, para expressar ideias, informações e sentimentos em língua inglesa.', objetoConhecimento: 'Interação oral' },
    { codigo: 'EF09LI02', descricao: 'Produzir textos orais e escritos em língua inglesa, com autonomia, para expressar ideias, informações e sentimentos.', objetoConhecimento: 'Produção oral e escrita' },
    { codigo: 'EF09LI03', descricao: 'Compreender textos orais e escritos em língua inglesa, com autonomia, para identificar informações gerais e específicas.', objetoConhecimento: 'Compreensão oral e escrita' },
    { codigo: 'EF09LI04', descricao: 'Utilizar estratégias de leitura (scanning, skimming, inferência) para compreender textos em língua inglesa.', objetoConhecimento: 'Estratégias de leitura' },
    { codigo: 'EF09LI05', descricao: 'Utilizar estratégias de escrita (planejamento, rascunho, revisão, edição) para produzir textos em língua inglesa.', objetoConhecimento: 'Estratégias de escrita' },
    { codigo: 'EF09LI06', descricao: 'Reconhecer e utilizar vocabulário em língua inglesa relacionado a temas do cotidiano, de interesse pessoal, de relevância social e de áreas específicas.', objetoConhecimento: 'Vocabulário' },
    { codigo: 'EF09LI07', descricao: 'Reconhecer e utilizar estruturas gramaticais em língua inglesa (tempos verbais complexos, voz passiva, reported speech, condicionais, inversão).', objetoConhecimento: 'Gramática' },
    { codigo: 'EF09LI08', descricao: 'Identificar e utilizar diferentes gêneros textuais em língua inglesa (notícias, artigos, resenhas, blogs, posts em redes sociais, textos acadêmicos).', objetoConhecimento: 'Gêneros textuais' },
    { codigo: 'EF09LI09', descricao: 'Valorizar a diversidade cultural presente na língua inglesa e em países de língua inglesa.', objetoConhecimento: 'Diversidade cultural' },
    { codigo: 'EF09LI10', descricao: 'Utilizar recursos tecnológicos (dicionários online, tradutores, aplicativos) para auxiliar na aprendizagem de língua inglesa.', objetoConhecimento: 'Recursos tecnológicos' },
    { codigo: 'EF09LI11', descricao: 'Participar de atividades lúdicas e jogos em língua inglesa para desenvolver a fluência e a confiança na comunicação.', objetoConhecimento: 'Atividades lúdicas' },
    { codigo: 'EF09LI12', descricao: 'Expressar opiniões e ideias em língua inglesa sobre temas do cotidiano, de interesse pessoal, de relevância social e de áreas específicas.', objetoConhecimento: 'Expressão de opiniões' },
    { codigo: 'EF09LI13', descricao: 'Apresentar informações sobre si mesmo e sobre outras pessoas em língua inglesa.', objetoConhecimento: 'Apresentação pessoal' },
    { codigo: 'EF09LI14', descricao: 'Descrever objetos, lugares e pessoas em língua inglesa.', objetoConhecimento: 'Descrição' },
    { codigo: 'EF09LI15', descricao: 'Narrar eventos e experiências em língua inglesa.', objetoConhecimento: 'Narração' },
    { codigo: 'EF09LI16', descricao: 'Fazer e responder perguntas em língua inglesa sobre temas do cotidiano, de interesse pessoal, de relevância social e de áreas específicas.', objetoConhecimento: 'Perguntas e respostas' },
    { codigo: 'EF09LI17', descricao: 'Dar e seguir instruções em língua inglesa.', objetoConhecimento: 'Instruções' },
    { codigo: 'EF09LI18', descricao: 'Expressar gostos e preferências em língua inglesa.', objetoConhecimento: 'Gostos e preferências' },
  ],
};
