COMPONENTE: Educação Física
ANO: 1º e 2º Ano
EF12EF01 | Experimentar, fruir e recriar diferentes brincadeiras e jogos da cultura popular presentes no contexto comunitário e regional, reconhecendo e respeitando as diferenças individuais de desempenho dos colegas. | Brincadeiras e jogos da cultura popular presentes no contexto comunitário e regional
EF12EF02 | Explicar, por meio de múltiplas linguagens (corporal, visual, oral e escrita), as brincadeiras e os jogos populares do contexto comunitário e regional, reconhecendo e valorizando a importância desses jogos e brincadeiras para suas culturas de origem. | Brincadeiras e jogos da cultura popular presentes no contexto comunitário e regional
EF12EF03 | Planejar e utilizar estratégias para resolver desafios de brincadeiras e jogos populares do contexto comunitário e regional, com base no reconhecimento das características dessas práticas. | Brincadeiras e jogos da cultura popular presentes no contexto comunitário e regional
EF12EF04 | Colaborar na proposição e na produção de alternativas para a prática, em outros momentos e espaços, de brincadeiras e jogos e demais práticas corporais tematizadas na escola, produzindo textos (orais, escritos, audiovisuais) para divulgá-las na escola e na comunidade. | Brincadeiras e jogos da cultura popular presentes no contexto comunitário e regional
EF12EF05 | Experimentar e fruir, prezando pelo trabalho coletivo e pelo protagonismo, diferentes elementos básicos da ginástica (equilíbrios, saltos, giros, rotações, acrobacias, com e sem aparelhos) e da ginástica geral, identificando a presença desses elementos em distintas práticas corporais. | Ginástica geral
EF12EF06 | Discutir a importância da observação das normas e das regras de segurança nas atividades de ginástica, com o objetivo de prevenir acidentes. | Ginástica geral
EF12EF07 | Experimentar e fruir e identificar diferentes elementos básicos da dança (ritmo, espaço, gestos) e as danças do contexto comunitário e regional, respeitando as diferenças individuais e de desempenho corporal. | Danças do contexto comunitário e regional
EF12EF08 | Planejar e utilizar estratégias para resolver desafios de elementos constitutivos das danças do contexto comunitário e regional, com base no reconhecimento das características dessas práticas. | Danças do contexto comunitário e regional
EF12EF09 | Participar em atividades de dança do contexto comunitário e regional, valorizando as manifestações artísticas e culturais de diferentes grupos. | Danças do contexto comunitário e regional
EF12EF10 | Experimentar e fruir diferentes tipos de esportes de marca e de precisão, identificando seus elementos comuns e criando estratégias individuais e coletivas para sua execução, prezando pelo trabalho coletivo e pelo protagonismo. | Esportes de marca; Esportes de precisão
EF12EF11 | Planejar e utilizar estratégias para resolver desafios de esportes de marca e de precisão, com base no reconhecimento das características dessas práticas. | Esportes de marca; Esportes de precisão
EF12EF12 | Identificar as características e as finalidades dos esportes de marca e de precisão, discutindo a importância da observação das normas e das regras de segurança nessas práticas. | Esportes de marca; Esportes de precisão

ANO: 3º ao 5º Ano
EF35EF01 | Experimentar e fruir brincadeiras e jogos populares do Brasil e do mundo, incluindo aqueles de matriz indígena e africana, e recriá-los, valorizando a importância desse patrimônio histórico-cultural. | Brincadeiras e jogos populares do Brasil e do mundo; Brincadeiras e jogos de matriz indígena e africana
EF35EF02 | Planejar e utilizar estratégias para possibilitar a participação segura de todos os alunos em brincadeiras e jogos populares do Brasil e de matriz indígena e africana. | Brincadeiras e jogos populares do Brasil e do mundo; Brincadeiras e jogos de matriz indígena e africana
EF35EF03 | Descrever, por meio de múltiplas linguagens (corporal, oral, escrita, audiovisual), as brincadeiras e os jogos populares do Brasil e de matriz indígena e africana, explicando suas características e a importância desse patrimônio histórico-cultural na preservação das diferentes culturas. | Brincadeiras e jogos populares do Brasil e do mundo; Brincadeiras e jogos de matriz indígena e africana
EF35EF04 | Recriar, individual e coletivamente, e experimentar, na escola e fora dela, brincadeiras e jogos populares do Brasil e do mundo, incluindo aqueles de matriz indígena e africana, e demais práticas corporais tematizadas na escola, adequando-as aos espaços públicos disponíveis. | Brincadeiras e jogos populares do Brasil e do mundo; Brincadeiras e jogos de matriz indígena e africana
EF35EF05 | Experimentar e fruir diversos tipos de esportes de campo e taco, rede/parede e invasão, identificando seus elementos comuns e criando estratégias individuais e coletivas para sua execução, prezando pelo trabalho coletivo e pelo protagonismo. | Esportes de campo e taco; Esportes de rede/parede; Esportes de invasão
EF35EF06 | Diferenciar os conceitos de jogo e esporte, identificando as características que os constituem na contemporaneidade e suas manifestações (profissional e comunitária/lazer). | Esportes de campo e taco; Esportes de rede/parede; Esportes de invasão
EF35EF07 | Planejar e utilizar estratégias para resolver desafios de esportes de campo e taco, rede/parede e invasão, com base no reconhecimento das características dessas práticas. | Esportes de campo e taco; Esportes de rede/parede; Esportes de invasão
EF35EF08 | Planejar e utilizar estratégias para resolver desafios na execução de elementos básicos da ginástica geral. | Ginástica geral
EF35EF09 | Experimentar, fruir e identificar elementos básicos da ginástica artística, da ginástica rítmica e da ginástica geral, identificando a presença desses elementos em distintas práticas corporais. | Ginástica geral
EF35EF10 | Comparar e identificar os elementos constitutivos comuns e diferentes das ginásticas artística e rítmica. | Ginástica geral
EF35EF11 | Experimentar e fruir diversas danças populares do Brasil e do mundo e danças de matriz indígena e africana, valorizando e respeitando os diferentes sentidos e significados dessas danças em suas culturas de origem. | Danças do Brasil e do mundo; Danças de matriz indígena e africana
EF35EF12 | Identificar os elementos constitutivos comuns e diferentes em danças populares do Brasil e do mundo e danças de matriz indígena e africana. | Danças do Brasil e do mundo; Danças de matriz indígena e africana
EF35EF13 | Planejar e utilizar estratégias para resolver desafios de elementos constitutivos das danças populares do Brasil e do mundo e das danças de matriz indígena e africana. | Danças do Brasil e do mundo; Danças de matriz indígena e africana
EF35EF14 | Experimentar e fruir diferentes lutas de matriz indígena e africana, valorizando e respeitando os diferentes sentidos e significados dessas lutas em suas culturas de origem. | Lutas de matriz indígena e africana
EF35EF15 | Planejar e utilizar estratégias básicas das lutas de matriz indígena e africana experimentadas, respeitando o colega como oponente e as normas de segurança. | Lutas de matriz indígena e africana

ANO: 6º e 7º Ano
EF67EF01 | Experimentar fruir, na escola e fora dela, jogos eletrônicos diversos, valorizando e respeitando os sentidos e significados atribuídos a eles por diferentes grupos sociais e etários. | Jogos eletrônicos
EF67EF02 | Identificar as transformações nas características dos jogos eletrônicos em função dos avanços das tecnologias e nas respectivas exigências corporais colocadas por esses diferentes tipos de jogos. | Jogos eletrônicos
EF67EF03 | Experimentar e fruir esportes de marca, precisão, invasão e técnico-combinatórios, valorizando o trabalho coletivo e o protagonismo. | Esportes de marca; Esportes de precisão; Esportes de invasão; Esportes técnico-combinatórios
EF67EF04 | Praticar um ou mais esportes de marca, precisão, invasão e técnico-combinatórios oferecidos pela escola, usando habilidades técnico-táticas básicas e respeitando regras. | Esportes de marca; Esportes de precisão; Esportes de invasão; Esportes técnico-combinatórios
EF67EF05 | Planejar e utilizar estratégias para resolver desafios de esportes de marca, precisão, invasão e técnico-combinatórios, com base no reconhecimento das características e contextos de cada modalidade. | Esportes de marca; Esportes de precisão; Esportes de invasão; Esportes técnico-combinatórios
EF67EF06 | Analisar as transformações históricas dos esportes de marca, precisão, invasão e técnico-combinatórios, bem como o processo de esportivização e a democratização de acesso. | Esportes de marca; Esportes de precisão; Esportes de invasão; Esportes técnico-combinatórios
EF67EF07 | Propor e produzir alternativas para experimentação dos esportes não disponíveis e/ou acessíveis na comunidade e das demais práticas corporais tematizadas na escola. | Esportes de marca; Esportes de precisão; Esportes de invasão; Esportes técnico-combinatórios
EF67EF08 | Experimentar e fruir exercícios físicos que solicitem diferentes capacidades físicas, identificando seus tipos (força, velocidade, resistência, flexibilidade) e as sensações corporais provocadas pela sua prática. | Ginástica de condicionamento físico
EF67EF09 | Construir, coletivamente, procedimentos e normas de convívio que viabilizem a participação de todos na prática de exercícios físicos, com o objetivo de promover a saúde. | Ginástica de condicionamento físico
EF67EF10 | Diferenciar exercício físico de atividade física e propor alternativas para a prática de exercícios físicos dentro e fora do ambiente escolar. | Ginástica de condicionamento físico
EF67EF11 | Experimentar e fruir diferentes danças urbanas, identificando seus elementos constitutivos (ritmo, espaço, gestos). | Danças urbanas
EF67EF12 | Planejar e utilizar estratégias para resolver desafios de elementos constitutivos das danças urbanas. | Danças urbanas
EF67EF13 | Diferenciar as danças urbanas das demais modalidades de dança, valorizando e respeitando os sentidos e significados atribuídos a eles por diferentes grupos sociais. | Danças urbanas
EF67EF14 | Experimentar e fruir diferentes lutas do Brasil, valorizando e respeitando os diferentes sentidos e significados dessas lutas em suas culturas de origem. | Lutas do Brasil
EF67EF15 | Planejar e utilizar estratégias básicas das lutas do Brasil, respeitando o colega como oponente e as normas de segurança. | Lutas do Brasil
EF67EF16 | Identificar as características das lutas do Brasil, reconhecendo as diferenças entre lutas e brigas e entre lutas e as demais práticas corporais. | Lutas do Brasil
EF67EF17 | Experimentar e fruir diferentes práticas corporais de aventura urbanas, valorizando a própria segurança e a dos demais, bem como o respeito ao patrimônio público e ao meio ambiente. | Práticas corporais de aventura urbanas
EF67EF18 | Identificar as características das práticas corporais de aventura urbanas, bem como os seus elementos constitutivos (equipamentos de segurança, instrumentos, indumentária, organização). | Práticas corporais de aventura urbanas
EF67EF19 | Planejar e utilizar estratégias para resolver desafios de práticas corporais de aventura urbanas, com base no reconhecimento das características dessas práticas. | Práticas corporais de aventura urbanas
EF67EF20 | Diferenciar as práticas corporais de aventura urbanas das demais modalidades de aventura, valorizando e respeitando os sentidos e significados atribuídos a elas por diferentes grupos sociais. | Práticas corporais de aventura urbanas
EF67EF21 | Identificar a origem das práticas corporais de aventura e as possibilidades de recriá-las, adequando-as aos espaços públicos disponíveis. | Práticas corporais de aventura urbanas

ANO: 8º e 9º Ano
EF89EF01 | Experimentar diferentes papéis (jogador, árbitro e técnico) e fruir os esportes de rede/parede, campo e taco, invasão e combate, valorizando o trabalho coletivo e o protagonismo. | Esportes de rede/parede; Esportes de campo e taco; Esportes de invasão; Esportes de combate
EF89EF02 | Praticar um ou mais esportes de rede/parede, campo e taco, invasão e combate oferecidos pela escola, usando habilidades técnico-táticas básicas. | Esportes de rede/parede; Esportes de campo e taco; Esportes de invasão; Esportes de combate
EF89EF03 | Formular e utilizar estratégias para solucionar os desafios técnicos e táticos, tanto nos esportes de campo e taco, rede/parede, invasão e combate como nas modalidades esportivas escolhidas para praticar de forma específica. | Esportes de rede/parede; Esportes de campo e taco; Esportes de invasão; Esportes de combate
EF89EF04 | Identificar os elementos técnicos ou táticos individuais, combinados e grupais que constituem os esportes de rede/parede, campo e taco, invasão e combate, bem como as modalidades esportivas escolhidas para praticar de forma específica. | Esportes de rede/parede; Esportes de campo e taco; Esportes de invasão; Esportes de combate
EF89EF05 | Identificar as transformações históricas do fenômeno esportivo e discutir alguns de seus problemas (doping, corrupção, violência etc.) e a forma como as mídias os apresentam. | Esportes de rede/parede; Esportes de campo e taco; Esportes de invasão; Esportes de combate
EF89EF06 | Verificar locais disponíveis na comunidade para a prática de esportes e das demais práticas corporais tematizadas na escola, propondo e produzindo alternativas para utilizá-los no tempo livre. | Esportes de rede/parede; Esportes de campo e taco; Esportes de invasão; Esportes de combate
EF89EF07 | Experimentar e fruir um ou mais programas de exercícios físicos, identificando as exigências internas (sensações corporais) e externas (ritmo, tempo, repetições etc.) e desdobramentos de cada prática no cotidiano. | Ginástica de condicionamento físico
EF89EF08 | Discutir as transformações históricas dos padrões de desempenho, saúde e beleza, considerando a forma como são apresentados nos diferentes meios de comunicação. | Ginástica de condicionamento físico
EF89EF09 | Construir, coletivamente, programas de exercícios físicos estabelecendo metas pessoais para a melhoria do condicionamento físico e da saúde. | Ginástica de condicionamento físico
EF89EF10 | Experimentar e fruir um ou mais tipos de ginástica de conscientização corporal, identificando as exigências e as sensações corporais provocadas pela sua prática. | Ginástica de conscientização corporal
EF89EF11 | Identificar as diferenças e semelhanças entre a ginástica de conscientização corporal e as de condicionamento físico e discutir como a prática de cada uma dessas manifestações pode contribuir para a melhoria da condição física e da saúde. | Ginástica de conscientização corporal
EF89EF12 | Experimentar, fruir e recriar danças de salão, valorizando a diversidade cultural e respeitando as diferenças individuais. | Danças de salão
EF89EF13 | Planejar e utilizar estratégias para resolver desafios de elementos constitutivos das danças de salão. | Danças de salão
EF89EF14 | Analisar as características (ritmo, passos, gestos, coreografia) das danças de salão, bem como suas transformações históricas e os grupos de origem. | Danças de salão
EF89EF15 | Analisar criticamente os preconceitos e os estereótipos relacionados ao universo das danças de salão e das demais práticas corporais, propondo alternativas para superá-los. | Danças de salão
EF89EF16 | Experimentar e fruir diferentes lutas do mundo, valorizando e respeitando os diferentes sentidos e significados dessas lutas em suas culturas de origem. | Lutas do mundo
EF89EF17 | Planejar e utilizar estratégias básicas das lutas do mundo, respeitando o colega como oponente e as normas de segurança. | Lutas do mundo
EF89EF18 | Identificar as características das lutas do mundo, bem como suas transformações históricas e os processos de esportivização. | Lutas do mundo
EF89EF19 | Experimentar e fruir diferentes práticas corporais de aventura na natureza, valorizando a própria segurança e a dos demais, bem como o respeito ao patrimônio natural. | Práticas corporais de aventura na natureza
EF89EF20 | Identificar as características das práticas corporais de aventura na natureza, bem como os seus elementos constitutivos (equipamentos de segurança, instrumentos, indumentária, organização). | Práticas corporais de aventura na natureza
EF89EF21 | Planejar e utilizar estratégias para resolver desafios de práticas corporais de aventura na natureza, com base no reconhecimento das características dessas práticas. | Práticas corporais de aventura na natureza
