
-- Criar tabela de sessões de flow para persistência de dados
CREATE TABLE IF NOT EXISTS flow_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  duration_seconds INTEGER NOT NULL,
  duration_formatted TEXT NOT NULL,
  subjects TEXT[] NOT NULL,
  progress INTEGER NOT NULL,
  session_goal TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Criar índice para melhorar a performance das consultas por usuário
CREATE INDEX IF NOT EXISTS flow_sessions_user_id_idx ON flow_sessions(user_id);

-- Permissões RLS (Row Level Security)
ALTER TABLE flow_sessions ENABLE ROW LEVEL SECURITY;

-- Política para que usuários possam acessar apenas suas próprias sessões
CREATE POLICY "Users can view their own flow sessions" 
ON flow_sessions FOR SELECT 
USING (auth.uid() = user_id);

-- Política para que usuários possam inserir suas próprias sessões
CREATE POLICY "Users can insert their own flow sessions" 
ON flow_sessions FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Política para que usuários possam atualizar suas próprias sessões
CREATE POLICY "Users can update their own flow sessions" 
ON flow_sessions FOR UPDATE 
USING (auth.uid() = user_id);

-- Política para que usuários possam deletar suas próprias sessões
CREATE POLICY "Users can delete their own flow sessions" 
ON flow_sessions FOR DELETE 
USING (auth.uid() = user_id);
