// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwmznopdzujcxzujijge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3bXpub3BkenVqY3h6dWppamdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNjM3NjgsImV4cCI6MjA1NTkzOTc2OH0.CiihfkrmPoyiE0R_nFONFHYgwIbq8BaNcYNEavQKRK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);